/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityResponse
 */
export interface ActivityResponse {
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    username: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    payload: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the ActivityResponse interface.
 */
export function instanceOfActivityResponse(value: object): value is ActivityResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ActivityResponseFromJSON(json: any): ActivityResponse {
    return ActivityResponseFromJSONTyped(json, false);
}

export function ActivityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['project_id'],
        'userId': json['user_id'],
        'username': json['username'],
        'displayName': json['display_name'],
        'type': json['type'],
        'payload': json['payload'],
        'createdAt': json['created_at'],
    };
}

export function ActivityResponseToJSON(json: any): ActivityResponse {
    return ActivityResponseToJSONTyped(json, false);
}

export function ActivityResponseToJSONTyped(value?: ActivityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project_id': value['projectId'],
        'user_id': value['userId'],
        'username': value['username'],
        'display_name': value['displayName'],
        'type': value['type'],
        'payload': value['payload'],
        'created_at': value['createdAt'],
    };
}

