/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityCreate
 */
export interface ActivityCreate {
    /**
     * 
     * @type {string}
     * @memberof ActivityCreate
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityCreate
     */
    payload?: string | null;
}

/**
 * Check if a given object implements the ActivityCreate interface.
 */
export function instanceOfActivityCreate(value: object): value is ActivityCreate {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ActivityCreateFromJSON(json: any): ActivityCreate {
    return ActivityCreateFromJSONTyped(json, false);
}

export function ActivityCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function ActivityCreateToJSON(json: any): ActivityCreate {
    return ActivityCreateToJSONTyped(json, false);
}

export function ActivityCreateToJSONTyped(value?: ActivityCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'payload': value['payload'],
    };
}

