/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One day of aggregated usage for a (user, provider, model, source) bucket.
 * @export
 * @interface AdminUsageDailyPoint
 */
export interface AdminUsageDailyPoint {
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    providerKey: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AdminUsageDailyPoint
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof AdminUsageDailyPoint
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof AdminUsageDailyPoint
     */
    outputTokens: number;
}

/**
 * Check if a given object implements the AdminUsageDailyPoint interface.
 */
export function instanceOfAdminUsageDailyPoint(value: object): value is AdminUsageDailyPoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    return true;
}

export function AdminUsageDailyPointFromJSON(json: any): AdminUsageDailyPoint {
    return AdminUsageDailyPointFromJSONTyped(json, false);
}

export function AdminUsageDailyPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsageDailyPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'userId': json['user_id'],
        'username': json['username'],
        'providerKey': json['provider_key'],
        'model': json['model'],
        'source': json['source'],
        'inputTokens': json['input_tokens'],
        'outputTokens': json['output_tokens'],
    };
}

export function AdminUsageDailyPointToJSON(json: any): AdminUsageDailyPoint {
    return AdminUsageDailyPointToJSONTyped(json, false);
}

export function AdminUsageDailyPointToJSONTyped(value?: AdminUsageDailyPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'user_id': value['userId'],
        'username': value['username'],
        'provider_key': value['providerKey'],
        'model': value['model'],
        'source': value['source'],
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
    };
}

