/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchModelsRequest
 */
export interface FetchModelsRequest {
    /**
     * 
     * @type {string}
     * @memberof FetchModelsRequest
     */
    type?: FetchModelsRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof FetchModelsRequest
     */
    baseUrl: string;
    /**
     * 
     * @type {string}
     * @memberof FetchModelsRequest
     */
    apiKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FetchModelsRequest
     */
    providerKey?: string | null;
}


/**
 * @export
 */
export const FetchModelsRequestTypeEnum = {
    Kimi: 'kimi',
    OpenaiLegacy: 'openai_legacy',
    OpenaiResponses: 'openai_responses',
    Anthropic: 'anthropic',
    GoogleGenai: 'google_genai',
    Gemini: 'gemini',
    Vertexai: 'vertexai'
} as const;
export type FetchModelsRequestTypeEnum = typeof FetchModelsRequestTypeEnum[keyof typeof FetchModelsRequestTypeEnum];


/**
 * Check if a given object implements the FetchModelsRequest interface.
 */
export function instanceOfFetchModelsRequest(value: object): value is FetchModelsRequest {
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    return true;
}

export function FetchModelsRequestFromJSON(json: any): FetchModelsRequest {
    return FetchModelsRequestFromJSONTyped(json, false);
}

export function FetchModelsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchModelsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'baseUrl': json['base_url'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'providerKey': json['provider_key'] == null ? undefined : json['provider_key'],
    };
}

export function FetchModelsRequestToJSON(json: any): FetchModelsRequest {
    return FetchModelsRequestToJSONTyped(json, false);
}

export function FetchModelsRequestToJSONTyped(value?: FetchModelsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'base_url': value['baseUrl'],
        'api_key': value['apiKey'],
        'provider_key': value['providerKey'],
    };
}

