/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderModelSpec } from './ProviderModelSpec';
import {
    ProviderModelSpecFromJSON,
    ProviderModelSpecFromJSONTyped,
    ProviderModelSpecToJSON,
    ProviderModelSpecToJSONTyped,
} from './ProviderModelSpec';

/**
 * 
 * @export
 * @interface FetchModelsResponse
 */
export interface FetchModelsResponse {
    /**
     * 
     * @type {Array<ProviderModelSpec>}
     * @memberof FetchModelsResponse
     */
    models: Array<ProviderModelSpec>;
}

/**
 * Check if a given object implements the FetchModelsResponse interface.
 */
export function instanceOfFetchModelsResponse(value: object): value is FetchModelsResponse {
    if (!('models' in value) || value['models'] === undefined) return false;
    return true;
}

export function FetchModelsResponseFromJSON(json: any): FetchModelsResponse {
    return FetchModelsResponseFromJSONTyped(json, false);
}

export function FetchModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchModelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'models': ((json['models'] as Array<any>).map(ProviderModelSpecFromJSON)),
    };
}

export function FetchModelsResponseToJSON(json: any): FetchModelsResponse {
    return FetchModelsResponseToJSONTyped(json, false);
}

export function FetchModelsResponseToJSONTyped(value?: FetchModelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': ((value['models'] as Array<any>).map(ProviderModelSpecToJSON)),
    };
}

