/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FsEntry
 */
export interface FsEntry {
    /**
     * 
     * @type {string}
     * @memberof FsEntry
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FsEntry
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof FsEntry
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof FsEntry
     */
    size?: number | null;
}

/**
 * Check if a given object implements the FsEntry interface.
 */
export function instanceOfFsEntry(value: object): value is FsEntry {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FsEntryFromJSON(json: any): FsEntry {
    return FsEntryFromJSONTyped(json, false);
}

export function FsEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FsEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'],
        'type': json['type'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function FsEntryToJSON(json: any): FsEntry {
    return FsEntryToJSONTyped(json, false);
}

export function FsEntryToJSONTyped(value?: FsEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
        'type': value['type'],
        'size': value['size'],
    };
}

