/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FsEntry } from './FsEntry';
import {
    FsEntryFromJSON,
    FsEntryFromJSONTyped,
    FsEntryToJSON,
    FsEntryToJSONTyped,
} from './FsEntry';

/**
 * 
 * @export
 * @interface FsListResponse
 */
export interface FsListResponse {
    /**
     * 
     * @type {Array<FsEntry>}
     * @memberof FsListResponse
     */
    entries: Array<FsEntry>;
}

/**
 * Check if a given object implements the FsListResponse interface.
 */
export function instanceOfFsListResponse(value: object): value is FsListResponse {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    return true;
}

export function FsListResponseFromJSON(json: any): FsListResponse {
    return FsListResponseFromJSONTyped(json, false);
}

export function FsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(FsEntryFromJSON)),
    };
}

export function FsListResponseToJSON(json: any): FsListResponse {
    return FsListResponseToJSONTyped(json, false);
}

export function FsListResponseToJSONTyped(value?: FsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(FsEntryToJSON)),
    };
}

