/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FsReadResponse
 */
export interface FsReadResponse {
    /**
     * 
     * @type {string}
     * @memberof FsReadResponse
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof FsReadResponse
     */
    path: string;
}

/**
 * Check if a given object implements the FsReadResponse interface.
 */
export function instanceOfFsReadResponse(value: object): value is FsReadResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FsReadResponseFromJSON(json: any): FsReadResponse {
    return FsReadResponseFromJSONTyped(json, false);
}

export function FsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'path': json['path'],
    };
}

export function FsReadResponseToJSON(json: any): FsReadResponse {
    return FsReadResponseToJSONTyped(json, false);
}

export function FsReadResponseToJSONTyped(value?: FsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'path': value['path'],
    };
}

