/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FsWriteRequest
 */
export interface FsWriteRequest {
    /**
     * 
     * @type {string}
     * @memberof FsWriteRequest
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof FsWriteRequest
     */
    content: string;
}

/**
 * Check if a given object implements the FsWriteRequest interface.
 */
export function instanceOfFsWriteRequest(value: object): value is FsWriteRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function FsWriteRequestFromJSON(json: any): FsWriteRequest {
    return FsWriteRequestFromJSONTyped(json, false);
}

export function FsWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FsWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'content': json['content'],
    };
}

export function FsWriteRequestToJSON(json: any): FsWriteRequest {
    return FsWriteRequestToJSONTyped(json, false);
}

export function FsWriteRequestToJSONTyped(value?: FsWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'content': value['content'],
    };
}

