/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitBranchResponse
 */
export interface GitBranchResponse {
    /**
     * 
     * @type {string}
     * @memberof GitBranchResponse
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof GitBranchResponse
     */
    current: boolean;
}

/**
 * Check if a given object implements the GitBranchResponse interface.
 */
export function instanceOfGitBranchResponse(value: object): value is GitBranchResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    return true;
}

export function GitBranchResponseFromJSON(json: any): GitBranchResponse {
    return GitBranchResponseFromJSONTyped(json, false);
}

export function GitBranchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitBranchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'current': json['current'],
    };
}

export function GitBranchResponseToJSON(json: any): GitBranchResponse {
    return GitBranchResponseToJSONTyped(json, false);
}

export function GitBranchResponseToJSONTyped(value?: GitBranchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'current': value['current'],
    };
}

