/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitCommitResponse
 */
export interface GitCommitResponse {
    /**
     * 
     * @type {string}
     * @memberof GitCommitResponse
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof GitCommitResponse
     */
    shortHash: string;
    /**
     * 
     * @type {string}
     * @memberof GitCommitResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof GitCommitResponse
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof GitCommitResponse
     */
    date: string;
}

/**
 * Check if a given object implements the GitCommitResponse interface.
 */
export function instanceOfGitCommitResponse(value: object): value is GitCommitResponse {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('shortHash' in value) || value['shortHash'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function GitCommitResponseFromJSON(json: any): GitCommitResponse {
    return GitCommitResponseFromJSONTyped(json, false);
}

export function GitCommitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitCommitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'shortHash': json['short_hash'],
        'message': json['message'],
        'author': json['author'],
        'date': json['date'],
    };
}

export function GitCommitResponseToJSON(json: any): GitCommitResponse {
    return GitCommitResponseToJSONTyped(json, false);
}

export function GitCommitResponseToJSONTyped(value?: GitCommitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
        'short_hash': value['shortHash'],
        'message': value['message'],
        'author': value['author'],
        'date': value['date'],
    };
}

