/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitCommitRequest
 */
export interface GitCommitRequest {
    /**
     * 
     * @type {string}
     * @memberof GitCommitRequest
     */
    message: string;
}

/**
 * Check if a given object implements the GitCommitRequest interface.
 */
export function instanceOfGitCommitRequest(value: object): value is GitCommitRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GitCommitRequestFromJSON(json: any): GitCommitRequest {
    return GitCommitRequestFromJSONTyped(json, false);
}

export function GitCommitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitCommitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GitCommitRequestToJSON(json: any): GitCommitRequest {
    return GitCommitRequestToJSONTyped(json, false);
}

export function GitCommitRequestToJSONTyped(value?: GitCommitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

