/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitDiffResponse
 */
export interface GitDiffResponse {
    /**
     * 
     * @type {string}
     * @memberof GitDiffResponse
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof GitDiffResponse
     */
    diff: string;
}

/**
 * Check if a given object implements the GitDiffResponse interface.
 */
export function instanceOfGitDiffResponse(value: object): value is GitDiffResponse {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('diff' in value) || value['diff'] === undefined) return false;
    return true;
}

export function GitDiffResponseFromJSON(json: any): GitDiffResponse {
    return GitDiffResponseFromJSONTyped(json, false);
}

export function GitDiffResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitDiffResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'diff': json['diff'],
    };
}

export function GitDiffResponseToJSON(json: any): GitDiffResponse {
    return GitDiffResponseToJSONTyped(json, false);
}

export function GitDiffResponseToJSONTyped(value?: GitDiffResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'diff': value['diff'],
    };
}

