/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitStatusResponse
 */
export interface GitStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GitStatusResponse
     */
    branch: string;
    /**
     * 
     * @type {number}
     * @memberof GitStatusResponse
     */
    ahead: number;
    /**
     * 
     * @type {number}
     * @memberof GitStatusResponse
     */
    behind: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitStatusResponse
     */
    modified: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitStatusResponse
     */
    staged: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GitStatusResponse
     */
    untracked: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof GitStatusResponse
     */
    clean: boolean;
}

/**
 * Check if a given object implements the GitStatusResponse interface.
 */
export function instanceOfGitStatusResponse(value: object): value is GitStatusResponse {
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('ahead' in value) || value['ahead'] === undefined) return false;
    if (!('behind' in value) || value['behind'] === undefined) return false;
    if (!('modified' in value) || value['modified'] === undefined) return false;
    if (!('staged' in value) || value['staged'] === undefined) return false;
    if (!('untracked' in value) || value['untracked'] === undefined) return false;
    if (!('clean' in value) || value['clean'] === undefined) return false;
    return true;
}

export function GitStatusResponseFromJSON(json: any): GitStatusResponse {
    return GitStatusResponseFromJSONTyped(json, false);
}

export function GitStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'],
        'ahead': json['ahead'],
        'behind': json['behind'],
        'modified': json['modified'],
        'staged': json['staged'],
        'untracked': json['untracked'],
        'clean': json['clean'],
    };
}

export function GitStatusResponseToJSON(json: any): GitStatusResponse {
    return GitStatusResponseToJSONTyped(json, false);
}

export function GitStatusResponseToJSONTyped(value?: GitStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'ahead': value['ahead'],
        'behind': value['behind'],
        'modified': value['modified'],
        'staged': value['staged'],
        'untracked': value['untracked'],
        'clean': value['clean'],
    };
}

