/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoalCreateRequest
 */
export interface GoalCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof GoalCreateRequest
     */
    objective: string;
    /**
     * 
     * @type {string}
     * @memberof GoalCreateRequest
     */
    criteria?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GoalCreateRequest
     */
    maxTurns?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GoalCreateRequest
     */
    maxTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GoalCreateRequest
     */
    maxSeconds?: number | null;
}

/**
 * Check if a given object implements the GoalCreateRequest interface.
 */
export function instanceOfGoalCreateRequest(value: object): value is GoalCreateRequest {
    if (!('objective' in value) || value['objective'] === undefined) return false;
    return true;
}

export function GoalCreateRequestFromJSON(json: any): GoalCreateRequest {
    return GoalCreateRequestFromJSONTyped(json, false);
}

export function GoalCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoalCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'objective': json['objective'],
        'criteria': json['criteria'] == null ? undefined : json['criteria'],
        'maxTurns': json['max_turns'] == null ? undefined : json['max_turns'],
        'maxTokens': json['max_tokens'] == null ? undefined : json['max_tokens'],
        'maxSeconds': json['max_seconds'] == null ? undefined : json['max_seconds'],
    };
}

export function GoalCreateRequestToJSON(json: any): GoalCreateRequest {
    return GoalCreateRequestToJSONTyped(json, false);
}

export function GoalCreateRequestToJSONTyped(value?: GoalCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objective': value['objective'],
        'criteria': value['criteria'],
        'max_turns': value['maxTurns'],
        'max_tokens': value['maxTokens'],
        'max_seconds': value['maxSeconds'],
    };
}

