/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One page of replayable history events (newest first-page or older).
 * @export
 * @interface HistoryPage
 */
export interface HistoryPage {
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryPage
     */
    events: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HistoryPage
     */
    oldestLine: number;
    /**
     * 
     * @type {boolean}
     * @memberof HistoryPage
     */
    hasMore: boolean;
    /**
     * 
     * @type {string}
     * @memberof HistoryPage
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof HistoryPage
     */
    turnBase?: number;
}

/**
 * Check if a given object implements the HistoryPage interface.
 */
export function instanceOfHistoryPage(value: object): value is HistoryPage {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('oldestLine' in value) || value['oldestLine'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function HistoryPageFromJSON(json: any): HistoryPage {
    return HistoryPageFromJSONTyped(json, false);
}

export function HistoryPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryPage {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'],
        'oldestLine': json['oldest_line'],
        'hasMore': json['has_more'],
        'source': json['source'] == null ? undefined : json['source'],
        'turnBase': json['turn_base'] == null ? undefined : json['turn_base'],
    };
}

export function HistoryPageToJSON(json: any): HistoryPage {
    return HistoryPageToJSONTyped(json, false);
}

export function HistoryPageToJSONTyped(value?: HistoryPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
        'oldest_line': value['oldestLine'],
        'has_more': value['hasMore'],
        'source': value['source'],
        'turn_base': value['turnBase'],
    };
}

