/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Set a model's context window size.
 * 
 * K3 example: 262144 (Moderato) / 524288 / 1048576 (Allegretto+ 1M). The
 * usable ceiling depends on the subscription tier of the account behind the
 * provider key.
 * @export
 * @interface ModelContextRequest
 */
export interface ModelContextRequest {
    /**
     * 
     * @type {number}
     * @memberof ModelContextRequest
     */
    maxContextSize: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelContextRequest
     */
    restartRunningSessions?: boolean;
}

/**
 * Check if a given object implements the ModelContextRequest interface.
 */
export function instanceOfModelContextRequest(value: object): value is ModelContextRequest {
    if (!('maxContextSize' in value) || value['maxContextSize'] === undefined) return false;
    return true;
}

export function ModelContextRequestFromJSON(json: any): ModelContextRequest {
    return ModelContextRequestFromJSONTyped(json, false);
}

export function ModelContextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelContextRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxContextSize': json['max_context_size'],
        'restartRunningSessions': json['restart_running_sessions'] == null ? undefined : json['restart_running_sessions'],
    };
}

export function ModelContextRequestToJSON(json: any): ModelContextRequest {
    return ModelContextRequestToJSONTyped(json, false);
}

export function ModelContextRequestToJSONTyped(value?: ModelContextRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_context_size': value['maxContextSize'],
        'restart_running_sessions': value['restartRunningSessions'],
    };
}

