/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdate
 */
export interface ProjectUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    workDir?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    gitRepoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdate
     */
    defaultModel?: string | null;
}

/**
 * Check if a given object implements the ProjectUpdate interface.
 */
export function instanceOfProjectUpdate(value: object): value is ProjectUpdate {
    return true;
}

export function ProjectUpdateFromJSON(json: any): ProjectUpdate {
    return ProjectUpdateFromJSONTyped(json, false);
}

export function ProjectUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'workDir': json['work_dir'] == null ? undefined : json['work_dir'],
        'gitRepoUrl': json['git_repo_url'] == null ? undefined : json['git_repo_url'],
        'defaultModel': json['default_model'] == null ? undefined : json['default_model'],
    };
}

export function ProjectUpdateToJSON(json: any): ProjectUpdate {
    return ProjectUpdateToJSONTyped(json, false);
}

export function ProjectUpdateToJSONTyped(value?: ProjectUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'work_dir': value['workDir'],
        'git_repo_url': value['gitRepoUrl'],
        'default_model': value['defaultModel'],
    };
}

