/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectCreate
 */
export interface ProjectCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    workDir?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    gitRepoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    defaultModel?: string | null;
}

/**
 * Check if a given object implements the ProjectCreate interface.
 */
export function instanceOfProjectCreate(value: object): value is ProjectCreate {
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function ProjectCreateFromJSON(json: any): ProjectCreate {
    return ProjectCreateFromJSONTyped(json, false);
}

export function ProjectCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['team_id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
        'workDir': json['work_dir'] == null ? undefined : json['work_dir'],
        'gitRepoUrl': json['git_repo_url'] == null ? undefined : json['git_repo_url'],
        'defaultModel': json['default_model'] == null ? undefined : json['default_model'],
    };
}

export function ProjectCreateToJSON(json: any): ProjectCreate {
    return ProjectCreateToJSONTyped(json, false);
}

export function ProjectCreateToJSONTyped(value?: ProjectCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team_id': value['teamId'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'work_dir': value['workDir'],
        'git_repo_url': value['gitRepoUrl'],
        'default_model': value['defaultModel'],
    };
}

