/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectMemberResponse } from './ProjectMemberResponse';
import {
    ProjectMemberResponseFromJSON,
    ProjectMemberResponseFromJSONTyped,
    ProjectMemberResponseToJSON,
    ProjectMemberResponseToJSONTyped,
} from './ProjectMemberResponse';

/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    teamId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    workDir: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    gitRepoUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    defaultModel: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    createdBy: string | null;
    /**
     * 
     * @type {Array<ProjectMemberResponse>}
     * @memberof ProjectResponse
     */
    members: Array<ProjectMemberResponse>;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('workDir' in value) || value['workDir'] === undefined) return false;
    if (!('gitRepoUrl' in value) || value['gitRepoUrl'] === undefined) return false;
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['team_id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'workDir': json['work_dir'],
        'gitRepoUrl': json['git_repo_url'],
        'defaultModel': json['default_model'],
        'createdBy': json['created_by'],
        'members': ((json['members'] as Array<any>).map(ProjectMemberResponseFromJSON)),
        'createdAt': json['created_at'],
    };
}

export function ProjectResponseToJSON(json: any): ProjectResponse {
    return ProjectResponseToJSONTyped(json, false);
}

export function ProjectResponseToJSONTyped(value?: ProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'team_id': value['teamId'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'work_dir': value['workDir'],
        'git_repo_url': value['gitRepoUrl'],
        'default_model': value['defaultModel'],
        'created_by': value['createdBy'],
        'members': ((value['members'] as Array<any>).map(ProjectMemberResponseToJSON)),
        'created_at': value['createdAt'],
    };
}

