/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectMemberResponse
 */
export interface ProjectMemberResponse {
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberResponse
     */
    joinedAt: string;
}

/**
 * Check if a given object implements the ProjectMemberResponse interface.
 */
export function instanceOfProjectMemberResponse(value: object): value is ProjectMemberResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function ProjectMemberResponseFromJSON(json: any): ProjectMemberResponse {
    return ProjectMemberResponseFromJSONTyped(json, false);
}

export function ProjectMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'username': json['username'],
        'displayName': json['display_name'],
        'role': json['role'],
        'joinedAt': json['joined_at'],
    };
}

export function ProjectMemberResponseToJSON(json: any): ProjectMemberResponse {
    return ProjectMemberResponseToJSONTyped(json, false);
}

export function ProjectMemberResponseToJSONTyped(value?: ProjectMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'username': value['username'],
        'display_name': value['displayName'],
        'role': value['role'],
        'joined_at': value['joinedAt'],
    };
}

