/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectMemberUpdateRole
 */
export interface ProjectMemberUpdateRole {
    /**
     * 
     * @type {string}
     * @memberof ProjectMemberUpdateRole
     */
    role: string;
}

/**
 * Check if a given object implements the ProjectMemberUpdateRole interface.
 */
export function instanceOfProjectMemberUpdateRole(value: object): value is ProjectMemberUpdateRole {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function ProjectMemberUpdateRoleFromJSON(json: any): ProjectMemberUpdateRole {
    return ProjectMemberUpdateRoleFromJSONTyped(json, false);
}

export function ProjectMemberUpdateRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectMemberUpdateRole {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function ProjectMemberUpdateRoleToJSON(json: any): ProjectMemberUpdateRole {
    return ProjectMemberUpdateRoleToJSONTyped(json, false);
}

export function ProjectMemberUpdateRoleToJSONTyped(value?: ProjectMemberUpdateRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

