/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderInfo } from './ProviderInfo';
import {
    ProviderInfoFromJSON,
    ProviderInfoFromJSONTyped,
    ProviderInfoToJSON,
    ProviderInfoToJSONTyped,
} from './ProviderInfo';

/**
 * 
 * @export
 * @interface ProviderListResponse
 */
export interface ProviderListResponse {
    /**
     * 
     * @type {string}
     * @memberof ProviderListResponse
     */
    defaultModel: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderListResponse
     */
    defaultThinking: boolean;
    /**
     * 
     * @type {Array<ProviderInfo>}
     * @memberof ProviderListResponse
     */
    providers: Array<ProviderInfo>;
}

/**
 * Check if a given object implements the ProviderListResponse interface.
 */
export function instanceOfProviderListResponse(value: object): value is ProviderListResponse {
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    if (!('defaultThinking' in value) || value['defaultThinking'] === undefined) return false;
    if (!('providers' in value) || value['providers'] === undefined) return false;
    return true;
}

export function ProviderListResponseFromJSON(json: any): ProviderListResponse {
    return ProviderListResponseFromJSONTyped(json, false);
}

export function ProviderListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'],
        'defaultThinking': json['default_thinking'],
        'providers': ((json['providers'] as Array<any>).map(ProviderInfoFromJSON)),
    };
}

export function ProviderListResponseToJSON(json: any): ProviderListResponse {
    return ProviderListResponseToJSONTyped(json, false);
}

export function ProviderListResponseToJSONTyped(value?: ProviderListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'providers': ((value['providers'] as Array<any>).map(ProviderInfoToJSON)),
    };
}

