/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A model served by a provider.
 * @export
 * @interface ProviderModelSpec
 */
export interface ProviderModelSpec {
    /**
     * 
     * @type {string}
     * @memberof ProviderModelSpec
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof ProviderModelSpec
     */
    maxContextSize?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderModelSpec
     */
    capabilities?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderModelSpec
     */
    displayName?: string | null;
}

/**
 * Check if a given object implements the ProviderModelSpec interface.
 */
export function instanceOfProviderModelSpec(value: object): value is ProviderModelSpec {
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function ProviderModelSpecFromJSON(json: any): ProviderModelSpec {
    return ProviderModelSpecFromJSONTyped(json, false);
}

export function ProviderModelSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderModelSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'],
        'maxContextSize': json['max_context_size'] == null ? undefined : json['max_context_size'],
        'capabilities': json['capabilities'] == null ? undefined : json['capabilities'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function ProviderModelSpecToJSON(json: any): ProviderModelSpec {
    return ProviderModelSpecToJSONTyped(json, false);
}

export function ProviderModelSpecToJSONTyped(value?: ProviderModelSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'max_context_size': value['maxContextSize'],
        'capabilities': value['capabilities'],
        'display_name': value['displayName'],
    };
}

