/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderModelSpec } from './ProviderModelSpec';
import {
    ProviderModelSpecFromJSON,
    ProviderModelSpecFromJSONTyped,
    ProviderModelSpecToJSON,
    ProviderModelSpecToJSONTyped,
} from './ProviderModelSpec';

/**
 * 
 * @export
 * @interface ProviderUpsertRequest
 */
export interface ProviderUpsertRequest {
    /**
     * 
     * @type {string}
     * @memberof ProviderUpsertRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderUpsertRequest
     */
    type: ProviderUpsertRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProviderUpsertRequest
     */
    baseUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderUpsertRequest
     */
    apiKey?: string | null;
    /**
     * 
     * @type {Array<ProviderModelSpec>}
     * @memberof ProviderUpsertRequest
     */
    models?: Array<ProviderModelSpec> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ProviderUpsertRequest
     */
    customHeaders?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderUpsertRequest
     */
    reasoningKey?: string | null;
}


/**
 * @export
 */
export const ProviderUpsertRequestTypeEnum = {
    Kimi: 'kimi',
    OpenaiLegacy: 'openai_legacy',
    OpenaiResponses: 'openai_responses',
    Anthropic: 'anthropic',
    GoogleGenai: 'google_genai',
    Gemini: 'gemini',
    Vertexai: 'vertexai'
} as const;
export type ProviderUpsertRequestTypeEnum = typeof ProviderUpsertRequestTypeEnum[keyof typeof ProviderUpsertRequestTypeEnum];


/**
 * Check if a given object implements the ProviderUpsertRequest interface.
 */
export function instanceOfProviderUpsertRequest(value: object): value is ProviderUpsertRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    return true;
}

export function ProviderUpsertRequestFromJSON(json: any): ProviderUpsertRequest {
    return ProviderUpsertRequestFromJSONTyped(json, false);
}

export function ProviderUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'type': json['type'],
        'baseUrl': json['base_url'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'models': json['models'] == null ? undefined : ((json['models'] as Array<any>).map(ProviderModelSpecFromJSON)),
        'customHeaders': json['custom_headers'] == null ? undefined : json['custom_headers'],
        'reasoningKey': json['reasoning_key'] == null ? undefined : json['reasoning_key'],
    };
}

export function ProviderUpsertRequestToJSON(json: any): ProviderUpsertRequest {
    return ProviderUpsertRequestToJSONTyped(json, false);
}

export function ProviderUpsertRequestToJSONTyped(value?: ProviderUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'type': value['type'],
        'base_url': value['baseUrl'],
        'api_key': value['apiKey'],
        'models': value['models'] == null ? undefined : ((value['models'] as Array<any>).map(ProviderModelSpecToJSON)),
        'custom_headers': value['customHeaders'],
        'reasoning_key': value['reasoningKey'],
    };
}

