/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderKeyUpsertRequest
 */
export interface ProviderKeyUpsertRequest {
    /**
     * 
     * @type {string}
     * @memberof ProviderKeyUpsertRequest
     */
    apiKey: string;
}

/**
 * Check if a given object implements the ProviderKeyUpsertRequest interface.
 */
export function instanceOfProviderKeyUpsertRequest(value: object): value is ProviderKeyUpsertRequest {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function ProviderKeyUpsertRequestFromJSON(json: any): ProviderKeyUpsertRequest {
    return ProviderKeyUpsertRequestFromJSONTyped(json, false);
}

export function ProviderKeyUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderKeyUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
    };
}

export function ProviderKeyUpsertRequestToJSON(json: any): ProviderKeyUpsertRequest {
    return ProviderKeyUpsertRequestToJSONTyped(json, false);
}

export function ProviderKeyUpsertRequestToJSONTyped(value?: ProviderKeyUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
    };
}

