/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderKeyResponse
 */
export interface ProviderKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof ProviderKeyResponse
     */
    providerKey: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderKeyResponse
     */
    hasApiKey: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProviderKeyResponse
     */
    createdAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProviderKeyResponse
     */
    updatedAt?: string | null;
}

/**
 * Check if a given object implements the ProviderKeyResponse interface.
 */
export function instanceOfProviderKeyResponse(value: object): value is ProviderKeyResponse {
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    if (!('hasApiKey' in value) || value['hasApiKey'] === undefined) return false;
    return true;
}

export function ProviderKeyResponseFromJSON(json: any): ProviderKeyResponse {
    return ProviderKeyResponseFromJSONTyped(json, false);
}

export function ProviderKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'providerKey': json['provider_key'],
        'hasApiKey': json['has_api_key'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ProviderKeyResponseToJSON(json: any): ProviderKeyResponse {
    return ProviderKeyResponseToJSONTyped(json, false);
}

export function ProviderKeyResponseToJSONTyped(value?: ProviderKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_key': value['providerKey'],
        'has_api_key': value['hasApiKey'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

