/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProviderModelSpec } from './ProviderModelSpec';
import {
    ProviderModelSpecFromJSON,
    ProviderModelSpecFromJSONTyped,
    ProviderModelSpecToJSON,
    ProviderModelSpecToJSONTyped,
} from './ProviderModelSpec';

/**
 * 
 * @export
 * @interface ProviderInfo
 */
export interface ProviderInfo {
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderInfo
     */
    baseUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProviderInfo
     */
    hasApiKey: boolean;
    /**
     * 
     * @type {Array<ProviderModelSpec>}
     * @memberof ProviderInfo
     */
    models: Array<ProviderModelSpec>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProviderInfo
     */
    modelKeys: Array<string>;
}

/**
 * Check if a given object implements the ProviderInfo interface.
 */
export function instanceOfProviderInfo(value: object): value is ProviderInfo {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('hasApiKey' in value) || value['hasApiKey'] === undefined) return false;
    if (!('models' in value) || value['models'] === undefined) return false;
    if (!('modelKeys' in value) || value['modelKeys'] === undefined) return false;
    return true;
}

export function ProviderInfoFromJSON(json: any): ProviderInfo {
    return ProviderInfoFromJSONTyped(json, false);
}

export function ProviderInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'type': json['type'],
        'baseUrl': json['base_url'],
        'hasApiKey': json['has_api_key'],
        'models': ((json['models'] as Array<any>).map(ProviderModelSpecFromJSON)),
        'modelKeys': json['model_keys'],
    };
}

export function ProviderInfoToJSON(json: any): ProviderInfo {
    return ProviderInfoToJSONTyped(json, false);
}

export function ProviderInfoToJSONTyped(value?: ProviderInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'type': value['type'],
        'base_url': value['baseUrl'],
        'has_api_key': value['hasApiKey'],
        'models': ((value['models'] as Array<any>).map(ProviderModelSpecToJSON)),
        'model_keys': value['modelKeys'],
    };
}

