/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FsListResponse } from './FsListResponse';
import {
    FsListResponseFromJSON,
    FsListResponseFromJSONTyped,
    FsListResponseToJSON,
    FsListResponseToJSONTyped,
} from './FsListResponse';
import type { FsEntry } from './FsEntry';
import {
    FsEntryFromJSON,
    FsEntryFromJSONTyped,
    FsEntryToJSON,
    FsEntryToJSONTyped,
} from './FsEntry';
import type { FsReadResponse } from './FsReadResponse';
import {
    FsReadResponseFromJSON,
    FsReadResponseFromJSONTyped,
    FsReadResponseToJSON,
    FsReadResponseToJSONTyped,
} from './FsReadResponse';

/**
 * 
 * @export
 * @interface ResponseReadFsApiV2ProjectsProjectIdFsGet
 */
export interface ResponseReadFsApiV2ProjectsProjectIdFsGet {
    /**
     * 
     * @type {Array<FsEntry>}
     * @memberof ResponseReadFsApiV2ProjectsProjectIdFsGet
     */
    entries: Array<FsEntry>;
    /**
     * 
     * @type {string}
     * @memberof ResponseReadFsApiV2ProjectsProjectIdFsGet
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseReadFsApiV2ProjectsProjectIdFsGet
     */
    path: string;
}

/**
 * Check if a given object implements the ResponseReadFsApiV2ProjectsProjectIdFsGet interface.
 */
export function instanceOfResponseReadFsApiV2ProjectsProjectIdFsGet(value: object): value is ResponseReadFsApiV2ProjectsProjectIdFsGet {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function ResponseReadFsApiV2ProjectsProjectIdFsGetFromJSON(json: any): ResponseReadFsApiV2ProjectsProjectIdFsGet {
    return ResponseReadFsApiV2ProjectsProjectIdFsGetFromJSONTyped(json, false);
}

export function ResponseReadFsApiV2ProjectsProjectIdFsGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseReadFsApiV2ProjectsProjectIdFsGet {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(FsEntryFromJSON)),
        'content': json['content'],
        'path': json['path'],
    };
}

export function ResponseReadFsApiV2ProjectsProjectIdFsGetToJSON(json: any): ResponseReadFsApiV2ProjectsProjectIdFsGet {
    return ResponseReadFsApiV2ProjectsProjectIdFsGetToJSONTyped(json, false);
}

export function ResponseReadFsApiV2ProjectsProjectIdFsGetToJSONTyped(value?: ResponseReadFsApiV2ProjectsProjectIdFsGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(FsEntryToJSON)),
        'content': value['content'],
        'path': value['path'],
    };
}

