/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectModelResponse
 */
export interface SelectModelResponse {
    /**
     * 
     * @type {string}
     * @memberof SelectModelResponse
     */
    defaultModel: string;
    /**
     * 
     * @type {boolean}
     * @memberof SelectModelResponse
     */
    defaultThinking: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof SelectModelResponse
     */
    restartedSessionIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SelectModelResponse
     */
    skippedBusySessionIds?: Array<string> | null;
}

/**
 * Check if a given object implements the SelectModelResponse interface.
 */
export function instanceOfSelectModelResponse(value: object): value is SelectModelResponse {
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    if (!('defaultThinking' in value) || value['defaultThinking'] === undefined) return false;
    return true;
}

export function SelectModelResponseFromJSON(json: any): SelectModelResponse {
    return SelectModelResponseFromJSONTyped(json, false);
}

export function SelectModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectModelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'],
        'defaultThinking': json['default_thinking'],
        'restartedSessionIds': json['restarted_session_ids'] == null ? undefined : json['restarted_session_ids'],
        'skippedBusySessionIds': json['skipped_busy_session_ids'] == null ? undefined : json['skipped_busy_session_ids'],
    };
}

export function SelectModelResponseToJSON(json: any): SelectModelResponse {
    return SelectModelResponseToJSONTyped(json, false);
}

export function SelectModelResponseToJSONTyped(value?: SelectModelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'restarted_session_ids': value['restartedSessionIds'],
        'skipped_busy_session_ids': value['skippedBusySessionIds'],
    };
}

