/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectModelRequest
 */
export interface SelectModelRequest {
    /**
     * 
     * @type {string}
     * @memberof SelectModelRequest
     */
    defaultModel: string;
    /**
     * 
     * @type {boolean}
     * @memberof SelectModelRequest
     */
    defaultThinking?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SelectModelRequest
     */
    restartRunningSessions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SelectModelRequest
     */
    forceRestartBusySessions?: boolean;
}

/**
 * Check if a given object implements the SelectModelRequest interface.
 */
export function instanceOfSelectModelRequest(value: object): value is SelectModelRequest {
    if (!('defaultModel' in value) || value['defaultModel'] === undefined) return false;
    return true;
}

export function SelectModelRequestFromJSON(json: any): SelectModelRequest {
    return SelectModelRequestFromJSONTyped(json, false);
}

export function SelectModelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectModelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'],
        'defaultThinking': json['default_thinking'] == null ? undefined : json['default_thinking'],
        'restartRunningSessions': json['restart_running_sessions'] == null ? undefined : json['restart_running_sessions'],
        'forceRestartBusySessions': json['force_restart_busy_sessions'] == null ? undefined : json['force_restart_busy_sessions'],
    };
}

export function SelectModelRequestToJSON(json: any): SelectModelRequest {
    return SelectModelRequestToJSONTyped(json, false);
}

export function SelectModelRequestToJSONTyped(value?: SelectModelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'restart_running_sessions': value['restartRunningSessions'],
        'force_restart_busy_sessions': value['forceRestartBusySessions'],
    };
}

