/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamMemberResponse } from './TeamMemberResponse';
import {
    TeamMemberResponseFromJSON,
    TeamMemberResponseFromJSONTyped,
    TeamMemberResponseToJSON,
    TeamMemberResponseToJSONTyped,
} from './TeamMemberResponse';

/**
 * 
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    timezone: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    ownerId: string;
    /**
     * 
     * @type {Array<TeamMemberResponse>}
     * @memberof TeamResponse
     */
    members: Array<TeamMemberResponse>;
    /**
     * 
     * @type {string}
     * @memberof TeamResponse
     */
    createdAt: string;
}

/**
 * Check if a given object implements the TeamResponse interface.
 */
export function instanceOfTeamResponse(value: object): value is TeamResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('ownerId' in value) || value['ownerId'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TeamResponseFromJSON(json: any): TeamResponse {
    return TeamResponseFromJSONTyped(json, false);
}

export function TeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'timezone': json['timezone'],
        'ownerId': json['owner_id'],
        'members': ((json['members'] as Array<any>).map(TeamMemberResponseFromJSON)),
        'createdAt': json['created_at'],
    };
}

export function TeamResponseToJSON(json: any): TeamResponse {
    return TeamResponseToJSONTyped(json, false);
}

export function TeamResponseToJSONTyped(value?: TeamResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'timezone': value['timezone'],
        'owner_id': value['ownerId'],
        'members': ((value['members'] as Array<any>).map(TeamMemberResponseToJSON)),
        'created_at': value['createdAt'],
    };
}

