/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamMemberResponse
 */
export interface TeamMemberResponse {
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberResponse
     */
    joinedAt: string;
}

/**
 * Check if a given object implements the TeamMemberResponse interface.
 */
export function instanceOfTeamMemberResponse(value: object): value is TeamMemberResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function TeamMemberResponseFromJSON(json: any): TeamMemberResponse {
    return TeamMemberResponseFromJSONTyped(json, false);
}

export function TeamMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'username': json['username'],
        'displayName': json['display_name'],
        'role': json['role'],
        'joinedAt': json['joined_at'],
    };
}

export function TeamMemberResponseToJSON(json: any): TeamMemberResponse {
    return TeamMemberResponseToJSONTyped(json, false);
}

export function TeamMemberResponseToJSONTyped(value?: TeamMemberResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'username': value['username'],
        'display_name': value['displayName'],
        'role': value['role'],
        'joined_at': value['joinedAt'],
    };
}

