/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamCreate
 */
export interface TeamCreate {
    /**
     * 
     * @type {string}
     * @memberof TeamCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TeamCreate
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TeamCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the TeamCreate interface.
 */
export function instanceOfTeamCreate(value: object): value is TeamCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function TeamCreateFromJSON(json: any): TeamCreate {
    return TeamCreateFromJSONTyped(json, false);
}

export function TeamCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TeamCreateToJSON(json: any): TeamCreate {
    return TeamCreateToJSONTyped(json, false);
}

export function TeamCreateToJSONTyped(value?: TeamCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
    };
}

