/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamMemberUpdateRole
 */
export interface TeamMemberUpdateRole {
    /**
     * 
     * @type {string}
     * @memberof TeamMemberUpdateRole
     */
    role: string;
}

/**
 * Check if a given object implements the TeamMemberUpdateRole interface.
 */
export function instanceOfTeamMemberUpdateRole(value: object): value is TeamMemberUpdateRole {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function TeamMemberUpdateRoleFromJSON(json: any): TeamMemberUpdateRole {
    return TeamMemberUpdateRoleFromJSONTyped(json, false);
}

export function TeamMemberUpdateRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMemberUpdateRole {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function TeamMemberUpdateRoleToJSON(json: any): TeamMemberUpdateRole {
    return TeamMemberUpdateRoleToJSONTyped(json, false);
}

export function TeamMemberUpdateRoleToJSONTyped(value?: TeamMemberUpdateRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

