/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamUpdate
 */
export interface TeamUpdate {
    /**
     * 
     * @type {string}
     * @memberof TeamUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamUpdate
     */
    timezone?: string | null;
}

/**
 * Check if a given object implements the TeamUpdate interface.
 */
export function instanceOfTeamUpdate(value: object): value is TeamUpdate {
    return true;
}

export function TeamUpdateFromJSON(json: any): TeamUpdate {
    return TeamUpdateFromJSONTyped(json, false);
}

export function TeamUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function TeamUpdateToJSON(json: any): TeamUpdate {
    return TeamUpdateToJSONTyped(json, false);
}

export function TeamUpdateToJSONTyped(value?: TeamUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'timezone': value['timezone'],
    };
}

