/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamProviderKeyResponse
 */
export interface TeamProviderKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof TeamProviderKeyResponse
     */
    providerKey: string;
    /**
     * 
     * @type {boolean}
     * @memberof TeamProviderKeyResponse
     */
    hasApiKey: boolean;
}

/**
 * Check if a given object implements the TeamProviderKeyResponse interface.
 */
export function instanceOfTeamProviderKeyResponse(value: object): value is TeamProviderKeyResponse {
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    if (!('hasApiKey' in value) || value['hasApiKey'] === undefined) return false;
    return true;
}

export function TeamProviderKeyResponseFromJSON(json: any): TeamProviderKeyResponse {
    return TeamProviderKeyResponseFromJSONTyped(json, false);
}

export function TeamProviderKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamProviderKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'providerKey': json['provider_key'],
        'hasApiKey': json['has_api_key'],
    };
}

export function TeamProviderKeyResponseToJSON(json: any): TeamProviderKeyResponse {
    return TeamProviderKeyResponseToJSONTyped(json, false);
}

export function TeamProviderKeyResponseToJSONTyped(value?: TeamProviderKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_key': value['providerKey'],
        'has_api_key': value['hasApiKey'],
    };
}

