/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamProviderKeyUpsertRequest
 */
export interface TeamProviderKeyUpsertRequest {
    /**
     * 
     * @type {string}
     * @memberof TeamProviderKeyUpsertRequest
     */
    apiKey: string;
}

/**
 * Check if a given object implements the TeamProviderKeyUpsertRequest interface.
 */
export function instanceOfTeamProviderKeyUpsertRequest(value: object): value is TeamProviderKeyUpsertRequest {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function TeamProviderKeyUpsertRequestFromJSON(json: any): TeamProviderKeyUpsertRequest {
    return TeamProviderKeyUpsertRequestFromJSONTyped(json, false);
}

export function TeamProviderKeyUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamProviderKeyUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
    };
}

export function TeamProviderKeyUpsertRequestToJSON(json: any): TeamProviderKeyUpsertRequest {
    return TeamProviderKeyUpsertRequestToJSONTyped(json, false);
}

export function TeamProviderKeyUpsertRequestToJSONTyped(value?: TeamProviderKeyUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
    };
}

