/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageSummary
 */
export interface UsageSummary {
    /**
     * 
     * @type {string}
     * @memberof UsageSummary
     */
    providerKey: string;
    /**
     * 
     * @type {string}
     * @memberof UsageSummary
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof UsageSummary
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummary
     */
    outputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummary
     */
    totalTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageSummary
     */
    quotaTokens?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UsageSummary
     */
    remainingTokens?: number | null;
}

/**
 * Check if a given object implements the UsageSummary interface.
 */
export function instanceOfUsageSummary(value: object): value is UsageSummary {
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    return true;
}

export function UsageSummaryFromJSON(json: any): UsageSummary {
    return UsageSummaryFromJSONTyped(json, false);
}

export function UsageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'providerKey': json['provider_key'],
        'source': json['source'],
        'inputTokens': json['input_tokens'],
        'outputTokens': json['output_tokens'],
        'totalTokens': json['total_tokens'],
        'quotaTokens': json['quota_tokens'] == null ? undefined : json['quota_tokens'],
        'remainingTokens': json['remaining_tokens'] == null ? undefined : json['remaining_tokens'],
    };
}

export function UsageSummaryToJSON(json: any): UsageSummary {
    return UsageSummaryToJSONTyped(json, false);
}

export function UsageSummaryToJSONTyped(value?: UsageSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_key': value['providerKey'],
        'source': value['source'],
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
        'total_tokens': value['totalTokens'],
        'quota_tokens': value['quotaTokens'],
        'remaining_tokens': value['remainingTokens'],
    };
}

