/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One day of aggregated usage for a (provider, model, source) bucket.
 * @export
 * @interface UsageDailyPoint
 */
export interface UsageDailyPoint {
    /**
     * 
     * @type {string}
     * @memberof UsageDailyPoint
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyPoint
     */
    providerKey: string;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyPoint
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof UsageDailyPoint
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof UsageDailyPoint
     */
    inputTokens: number;
    /**
     * 
     * @type {number}
     * @memberof UsageDailyPoint
     */
    outputTokens: number;
}

/**
 * Check if a given object implements the UsageDailyPoint interface.
 */
export function instanceOfUsageDailyPoint(value: object): value is UsageDailyPoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('providerKey' in value) || value['providerKey'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('inputTokens' in value) || value['inputTokens'] === undefined) return false;
    if (!('outputTokens' in value) || value['outputTokens'] === undefined) return false;
    return true;
}

export function UsageDailyPointFromJSON(json: any): UsageDailyPoint {
    return UsageDailyPointFromJSONTyped(json, false);
}

export function UsageDailyPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageDailyPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'providerKey': json['provider_key'],
        'model': json['model'],
        'source': json['source'],
        'inputTokens': json['input_tokens'],
        'outputTokens': json['output_tokens'],
    };
}

export function UsageDailyPointToJSON(json: any): UsageDailyPoint {
    return UsageDailyPointToJSONTyped(json, false);
}

export function UsageDailyPointToJSONTyped(value?: UsageDailyPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'provider_key': value['providerKey'],
        'model': value['model'],
        'source': value['source'],
        'input_tokens': value['inputTokens'],
        'output_tokens': value['outputTokens'],
    };
}

