/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRoleUpdate
 */
export interface UserRoleUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserRoleUpdate
     */
    role: string;
}

/**
 * Check if a given object implements the UserRoleUpdate interface.
 */
export function instanceOfUserRoleUpdate(value: object): value is UserRoleUpdate {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserRoleUpdateFromJSON(json: any): UserRoleUpdate {
    return UserRoleUpdateFromJSONTyped(json, false);
}

export function UserRoleUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoleUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'],
    };
}

export function UserRoleUpdateToJSON(json: any): UserRoleUpdate {
    return UserRoleUpdateToJSONTyped(json, false);
}

export function UserRoleUpdateToJSONTyped(value?: UserRoleUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

