/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    envTemplate?: string | null;
}

/**
 * Check if a given object implements the UserProfileUpdate interface.
 */
export function instanceOfUserProfileUpdate(value: object): value is UserProfileUpdate {
    return true;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'envTemplate': json['env_template'] == null ? undefined : json['env_template'],
    };
}

export function UserProfileUpdateToJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateToJSONTyped(json, false);
}

export function UserProfileUpdateToJSONTyped(value?: UserProfileUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'avatar_url': value['avatarUrl'],
        'env_template': value['envTemplate'],
    };
}

