/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminUsageDailyPoint,
  HTTPValidationError,
} from '../models/index';
import {
    AdminUsageDailyPointFromJSON,
    AdminUsageDailyPointToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetAdminUsageApiV2AdminUsageGetRequest {
    days?: number;
    tz?: string | null;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Per-day token usage for ALL users (admin only).  Same bucketing as ``/users/me/usage/daily`` but additionally grouped by user, with ``username`` resolved via a join. Ordered by date, then user. Days are calendar days in the ``tz`` timezone (IANA name, default UTC). ``days`` is clamped to [1, 90].
     * Get Admin Usage
     */
    async getAdminUsageApiV2AdminUsageGetRaw(requestParameters: GetAdminUsageApiV2AdminUsageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminUsageDailyPoint>>> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        if (requestParameters['tz'] != null) {
            queryParameters['tz'] = requestParameters['tz'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/admin/usage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminUsageDailyPointFromJSON));
    }

    /**
     * Per-day token usage for ALL users (admin only).  Same bucketing as ``/users/me/usage/daily`` but additionally grouped by user, with ``username`` resolved via a join. Ordered by date, then user. Days are calendar days in the ``tz`` timezone (IANA name, default UTC). ``days`` is clamped to [1, 90].
     * Get Admin Usage
     */
    async getAdminUsageApiV2AdminUsageGet(requestParameters: GetAdminUsageApiV2AdminUsageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminUsageDailyPoint>> {
        const response = await this.getAdminUsageApiV2AdminUsageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
