/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FsWriteRequest,
  HTTPValidationError,
  ResponseReadFsApiV2ProjectsProjectIdFsGet,
} from '../models/index';
import {
    FsWriteRequestFromJSON,
    FsWriteRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ResponseReadFsApiV2ProjectsProjectIdFsGetFromJSON,
    ResponseReadFsApiV2ProjectsProjectIdFsGetToJSON,
} from '../models/index';

export interface CompressFsApiV2ProjectsProjectIdFsCompressPostRequest {
    projectId: string;
    path: string;
    archive: string;
}

export interface CopyFsApiV2ProjectsProjectIdFsCopyPostRequest {
    projectId: string;
    src: string;
    dst: string;
}

export interface DeleteFsApiV2ProjectsProjectIdFsDeleteRequest {
    projectId: string;
    path: string;
}

export interface DownloadFsApiV2ProjectsProjectIdFsDownloadGetRequest {
    projectId: string;
    path: string;
}

export interface ExtractFsApiV2ProjectsProjectIdFsExtractPostRequest {
    projectId: string;
    archive: string;
    dest?: string;
}

export interface MoveFsApiV2ProjectsProjectIdFsMovePostRequest {
    projectId: string;
    src: string;
    dst: string;
}

export interface ReadFsApiV2ProjectsProjectIdFsGetRequest {
    projectId: string;
    path?: string;
}

export interface UploadFsApiV2ProjectsProjectIdFsUploadPostRequest {
    projectId: string;
    file: Blob;
    path?: string;
}

export interface WriteFsApiV2ProjectsProjectIdFsPostRequest {
    projectId: string;
    fsWriteRequest: FsWriteRequest;
}

/**
 * 
 */
export class FsApi extends runtime.BaseAPI {

    /**
     * Compress a file or directory into a zip archive inside the project.
     * Compress Fs
     */
    async compressFsApiV2ProjectsProjectIdFsCompressPostRaw(requestParameters: CompressFsApiV2ProjectsProjectIdFsCompressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling compressFsApiV2ProjectsProjectIdFsCompressPost().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling compressFsApiV2ProjectsProjectIdFsCompressPost().'
            );
        }

        if (requestParameters['archive'] == null) {
            throw new runtime.RequiredError(
                'archive',
                'Required parameter "archive" was null or undefined when calling compressFsApiV2ProjectsProjectIdFsCompressPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['archive'] != null) {
            queryParameters['archive'] = requestParameters['archive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/compress`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Compress a file or directory into a zip archive inside the project.
     * Compress Fs
     */
    async compressFsApiV2ProjectsProjectIdFsCompressPost(requestParameters: CompressFsApiV2ProjectsProjectIdFsCompressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.compressFsApiV2ProjectsProjectIdFsCompressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Copy a file or directory to another path inside the project.
     * Copy Fs
     */
    async copyFsApiV2ProjectsProjectIdFsCopyPostRaw(requestParameters: CopyFsApiV2ProjectsProjectIdFsCopyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling copyFsApiV2ProjectsProjectIdFsCopyPost().'
            );
        }

        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling copyFsApiV2ProjectsProjectIdFsCopyPost().'
            );
        }

        if (requestParameters['dst'] == null) {
            throw new runtime.RequiredError(
                'dst',
                'Required parameter "dst" was null or undefined when calling copyFsApiV2ProjectsProjectIdFsCopyPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        if (requestParameters['dst'] != null) {
            queryParameters['dst'] = requestParameters['dst'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/copy`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Copy a file or directory to another path inside the project.
     * Copy Fs
     */
    async copyFsApiV2ProjectsProjectIdFsCopyPost(requestParameters: CopyFsApiV2ProjectsProjectIdFsCopyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.copyFsApiV2ProjectsProjectIdFsCopyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a file or directory inside the project working directory.
     * Delete Fs
     */
    async deleteFsApiV2ProjectsProjectIdFsDeleteRaw(requestParameters: DeleteFsApiV2ProjectsProjectIdFsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteFsApiV2ProjectsProjectIdFsDelete().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling deleteFsApiV2ProjectsProjectIdFsDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a file or directory inside the project working directory.
     * Delete Fs
     */
    async deleteFsApiV2ProjectsProjectIdFsDelete(requestParameters: DeleteFsApiV2ProjectsProjectIdFsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.deleteFsApiV2ProjectsProjectIdFsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download a file from the project working directory.
     * Download Fs
     */
    async downloadFsApiV2ProjectsProjectIdFsDownloadGetRaw(requestParameters: DownloadFsApiV2ProjectsProjectIdFsDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling downloadFsApiV2ProjectsProjectIdFsDownloadGet().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling downloadFsApiV2ProjectsProjectIdFsDownloadGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/download`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download a file from the project working directory.
     * Download Fs
     */
    async downloadFsApiV2ProjectsProjectIdFsDownloadGet(requestParameters: DownloadFsApiV2ProjectsProjectIdFsDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadFsApiV2ProjectsProjectIdFsDownloadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Extract a zip archive inside the project working directory.
     * Extract Fs
     */
    async extractFsApiV2ProjectsProjectIdFsExtractPostRaw(requestParameters: ExtractFsApiV2ProjectsProjectIdFsExtractPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling extractFsApiV2ProjectsProjectIdFsExtractPost().'
            );
        }

        if (requestParameters['archive'] == null) {
            throw new runtime.RequiredError(
                'archive',
                'Required parameter "archive" was null or undefined when calling extractFsApiV2ProjectsProjectIdFsExtractPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['archive'] != null) {
            queryParameters['archive'] = requestParameters['archive'];
        }

        if (requestParameters['dest'] != null) {
            queryParameters['dest'] = requestParameters['dest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/extract`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Extract a zip archive inside the project working directory.
     * Extract Fs
     */
    async extractFsApiV2ProjectsProjectIdFsExtractPost(requestParameters: ExtractFsApiV2ProjectsProjectIdFsExtractPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.extractFsApiV2ProjectsProjectIdFsExtractPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Move (rename) a file or directory to another path inside the project.
     * Move Fs
     */
    async moveFsApiV2ProjectsProjectIdFsMovePostRaw(requestParameters: MoveFsApiV2ProjectsProjectIdFsMovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling moveFsApiV2ProjectsProjectIdFsMovePost().'
            );
        }

        if (requestParameters['src'] == null) {
            throw new runtime.RequiredError(
                'src',
                'Required parameter "src" was null or undefined when calling moveFsApiV2ProjectsProjectIdFsMovePost().'
            );
        }

        if (requestParameters['dst'] == null) {
            throw new runtime.RequiredError(
                'dst',
                'Required parameter "dst" was null or undefined when calling moveFsApiV2ProjectsProjectIdFsMovePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['src'] != null) {
            queryParameters['src'] = requestParameters['src'];
        }

        if (requestParameters['dst'] != null) {
            queryParameters['dst'] = requestParameters['dst'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/move`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Move (rename) a file or directory to another path inside the project.
     * Move Fs
     */
    async moveFsApiV2ProjectsProjectIdFsMovePost(requestParameters: MoveFsApiV2ProjectsProjectIdFsMovePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.moveFsApiV2ProjectsProjectIdFsMovePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read Fs
     */
    async readFsApiV2ProjectsProjectIdFsGetRaw(requestParameters: ReadFsApiV2ProjectsProjectIdFsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseReadFsApiV2ProjectsProjectIdFsGet>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling readFsApiV2ProjectsProjectIdFsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseReadFsApiV2ProjectsProjectIdFsGetFromJSON(jsonValue));
    }

    /**
     * Read Fs
     */
    async readFsApiV2ProjectsProjectIdFsGet(requestParameters: ReadFsApiV2ProjectsProjectIdFsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseReadFsApiV2ProjectsProjectIdFsGet> {
        const response = await this.readFsApiV2ProjectsProjectIdFsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a file into the project working directory.  The `path` query parameter is the relative directory where the file should be stored. The uploaded file\'s original filename is appended to it.
     * Upload Fs
     */
    async uploadFsApiV2ProjectsProjectIdFsUploadPostRaw(requestParameters: UploadFsApiV2ProjectsProjectIdFsUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling uploadFsApiV2ProjectsProjectIdFsUploadPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadFsApiV2ProjectsProjectIdFsUploadPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs/upload`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Upload a file into the project working directory.  The `path` query parameter is the relative directory where the file should be stored. The uploaded file\'s original filename is appended to it.
     * Upload Fs
     */
    async uploadFsApiV2ProjectsProjectIdFsUploadPost(requestParameters: UploadFsApiV2ProjectsProjectIdFsUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.uploadFsApiV2ProjectsProjectIdFsUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Write Fs
     */
    async writeFsApiV2ProjectsProjectIdFsPostRaw(requestParameters: WriteFsApiV2ProjectsProjectIdFsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling writeFsApiV2ProjectsProjectIdFsPost().'
            );
        }

        if (requestParameters['fsWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'fsWriteRequest',
                'Required parameter "fsWriteRequest" was null or undefined when calling writeFsApiV2ProjectsProjectIdFsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/fs`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FsWriteRequestToJSON(requestParameters['fsWriteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Write Fs
     */
    async writeFsApiV2ProjectsProjectIdFsPost(requestParameters: WriteFsApiV2ProjectsProjectIdFsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.writeFsApiV2ProjectsProjectIdFsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
