/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GitBranchResponse,
  GitCommitRequest,
  GitCommitResponse,
  GitDiffResponse,
  GitStatusResponse,
  HTTPValidationError,
} from '../models/index';
import {
    GitBranchResponseFromJSON,
    GitBranchResponseToJSON,
    GitCommitRequestFromJSON,
    GitCommitRequestToJSON,
    GitCommitResponseFromJSON,
    GitCommitResponseToJSON,
    GitDiffResponseFromJSON,
    GitDiffResponseToJSON,
    GitStatusResponseFromJSON,
    GitStatusResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GitBranchesApiV2ProjectsProjectIdGitBranchesGetRequest {
    projectId: string;
}

export interface GitCommitApiV2ProjectsProjectIdGitCommitPostRequest {
    projectId: string;
    gitCommitRequest: GitCommitRequest;
}

export interface GitDiffApiV2ProjectsProjectIdGitDiffGetRequest {
    projectId: string;
    staged?: boolean;
    path?: string | null;
}

export interface GitLogApiV2ProjectsProjectIdGitLogGetRequest {
    projectId: string;
    limit?: number;
}

export interface GitStatusApiV2ProjectsProjectIdGitStatusGetRequest {
    projectId: string;
}

/**
 * 
 */
export class GitApi extends runtime.BaseAPI {

    /**
     * Git Branches
     */
    async gitBranchesApiV2ProjectsProjectIdGitBranchesGetRaw(requestParameters: GitBranchesApiV2ProjectsProjectIdGitBranchesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GitBranchResponse>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling gitBranchesApiV2ProjectsProjectIdGitBranchesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/git/branches`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GitBranchResponseFromJSON));
    }

    /**
     * Git Branches
     */
    async gitBranchesApiV2ProjectsProjectIdGitBranchesGet(requestParameters: GitBranchesApiV2ProjectsProjectIdGitBranchesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GitBranchResponse>> {
        const response = await this.gitBranchesApiV2ProjectsProjectIdGitBranchesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Git Commit
     */
    async gitCommitApiV2ProjectsProjectIdGitCommitPostRaw(requestParameters: GitCommitApiV2ProjectsProjectIdGitCommitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling gitCommitApiV2ProjectsProjectIdGitCommitPost().'
            );
        }

        if (requestParameters['gitCommitRequest'] == null) {
            throw new runtime.RequiredError(
                'gitCommitRequest',
                'Required parameter "gitCommitRequest" was null or undefined when calling gitCommitApiV2ProjectsProjectIdGitCommitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/git/commit`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GitCommitRequestToJSON(requestParameters['gitCommitRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Git Commit
     */
    async gitCommitApiV2ProjectsProjectIdGitCommitPost(requestParameters: GitCommitApiV2ProjectsProjectIdGitCommitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.gitCommitApiV2ProjectsProjectIdGitCommitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Git Diff
     */
    async gitDiffApiV2ProjectsProjectIdGitDiffGetRaw(requestParameters: GitDiffApiV2ProjectsProjectIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GitDiffResponse>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling gitDiffApiV2ProjectsProjectIdGitDiffGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['staged'] != null) {
            queryParameters['staged'] = requestParameters['staged'];
        }

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/git/diff`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GitDiffResponseFromJSON));
    }

    /**
     * Git Diff
     */
    async gitDiffApiV2ProjectsProjectIdGitDiffGet(requestParameters: GitDiffApiV2ProjectsProjectIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GitDiffResponse>> {
        const response = await this.gitDiffApiV2ProjectsProjectIdGitDiffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Git Log
     */
    async gitLogApiV2ProjectsProjectIdGitLogGetRaw(requestParameters: GitLogApiV2ProjectsProjectIdGitLogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GitCommitResponse>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling gitLogApiV2ProjectsProjectIdGitLogGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/git/log`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GitCommitResponseFromJSON));
    }

    /**
     * Git Log
     */
    async gitLogApiV2ProjectsProjectIdGitLogGet(requestParameters: GitLogApiV2ProjectsProjectIdGitLogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GitCommitResponse>> {
        const response = await this.gitLogApiV2ProjectsProjectIdGitLogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Git Status
     */
    async gitStatusApiV2ProjectsProjectIdGitStatusGetRaw(requestParameters: GitStatusApiV2ProjectsProjectIdGitStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitStatusResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling gitStatusApiV2ProjectsProjectIdGitStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/git/status`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GitStatusResponseFromJSON(jsonValue));
    }

    /**
     * Git Status
     */
    async gitStatusApiV2ProjectsProjectIdGitStatusGet(requestParameters: GitStatusApiV2ProjectsProjectIdGitStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitStatusResponse> {
        const response = await this.gitStatusApiV2ProjectsProjectIdGitStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
