/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ProxyPxV1PathPostRequest {
    path: string;
}

export interface ProxyPxV1PathPost0Request {
    path: string;
}

export interface ProxyPxV1PathPost1Request {
    path: string;
}

export interface ProxyPxV1PathPost2Request {
    path: string;
}

export interface ProxyPxV1PathPost3Request {
    path: string;
}

/**
 * 
 */
export class KeyproxyApi extends runtime.BaseAPI {

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPostRaw(requestParameters: ProxyPxV1PathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling proxyPxV1PathPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/px/v1/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost(requestParameters: ProxyPxV1PathPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyPxV1PathPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_1Raw(requestParameters: ProxyPxV1PathPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling proxyPxV1PathPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/px/v1/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_1(requestParameters: ProxyPxV1PathPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyPxV1PathPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_2Raw(requestParameters: ProxyPxV1PathPost1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling proxyPxV1PathPost_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/px/v1/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_2(requestParameters: ProxyPxV1PathPost1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyPxV1PathPost_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_3Raw(requestParameters: ProxyPxV1PathPost2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling proxyPxV1PathPost_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/px/v1/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_3(requestParameters: ProxyPxV1PathPost2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyPxV1PathPost_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_4Raw(requestParameters: ProxyPxV1PathPost3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling proxyPxV1PathPost_4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/px/v1/{path}`;
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Forward a provider API call with the resolved real key.
     * Proxy
     */
    async proxyPxV1PathPost_4(requestParameters: ProxyPxV1PathPost3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.proxyPxV1PathPost_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
