/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActivityCreate,
  ActivityResponse,
  HTTPValidationError,
  ProjectCreate,
  ProjectMemberUpdateRole,
  ProjectResponse,
  ProjectUpdate,
} from '../models/index';
import {
    ActivityCreateFromJSON,
    ActivityCreateToJSON,
    ActivityResponseFromJSON,
    ActivityResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProjectCreateFromJSON,
    ProjectCreateToJSON,
    ProjectMemberUpdateRoleFromJSON,
    ProjectMemberUpdateRoleToJSON,
    ProjectResponseFromJSON,
    ProjectResponseToJSON,
    ProjectUpdateFromJSON,
    ProjectUpdateToJSON,
} from '../models/index';

export interface AddProjectMemberApiV2ProjectsProjectIdMembersPostRequest {
    projectId: string;
    userId: string;
    role?: string;
}

export interface CreateProjectActivityApiV2ProjectsProjectIdActivitiesPostRequest {
    projectId: string;
    activityCreate: ActivityCreate;
}

export interface CreateProjectApiV2ProjectsPostRequest {
    projectCreate: ProjectCreate;
}

export interface GetProjectApiV2ProjectsProjectIdGetRequest {
    projectId: string;
}

export interface ListProjectActivitiesApiV2ProjectsProjectIdActivitiesGetRequest {
    projectId: string;
    limit?: number;
}

export interface ListProjectsApiV2ProjectsGetRequest {
    teamId?: string | null;
}

export interface RemoveProjectMemberApiV2ProjectsProjectIdMembersMemberIdDeleteRequest {
    projectId: string;
    memberId: string;
}

export interface UpdateProjectApiV2ProjectsProjectIdPatchRequest {
    projectId: string;
    projectUpdate: ProjectUpdate;
}

export interface UpdateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatchRequest {
    projectId: string;
    memberId: string;
    projectMemberUpdateRole: ProjectMemberUpdateRole;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Add Project Member
     */
    async addProjectMemberApiV2ProjectsProjectIdMembersPostRaw(requestParameters: AddProjectMemberApiV2ProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addProjectMemberApiV2ProjectsProjectIdMembersPost().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addProjectMemberApiV2ProjectsProjectIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/members`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Add Project Member
     */
    async addProjectMemberApiV2ProjectsProjectIdMembersPost(requestParameters: AddProjectMemberApiV2ProjectsProjectIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.addProjectMemberApiV2ProjectsProjectIdMembersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Project Activity
     */
    async createProjectActivityApiV2ProjectsProjectIdActivitiesPostRaw(requestParameters: CreateProjectActivityApiV2ProjectsProjectIdActivitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActivityResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createProjectActivityApiV2ProjectsProjectIdActivitiesPost().'
            );
        }

        if (requestParameters['activityCreate'] == null) {
            throw new runtime.RequiredError(
                'activityCreate',
                'Required parameter "activityCreate" was null or undefined when calling createProjectActivityApiV2ProjectsProjectIdActivitiesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/activities`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActivityCreateToJSON(requestParameters['activityCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActivityResponseFromJSON(jsonValue));
    }

    /**
     * Create Project Activity
     */
    async createProjectActivityApiV2ProjectsProjectIdActivitiesPost(requestParameters: CreateProjectActivityApiV2ProjectsProjectIdActivitiesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActivityResponse> {
        const response = await this.createProjectActivityApiV2ProjectsProjectIdActivitiesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Project
     */
    async createProjectApiV2ProjectsPostRaw(requestParameters: CreateProjectApiV2ProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectCreate'] == null) {
            throw new runtime.RequiredError(
                'projectCreate',
                'Required parameter "projectCreate" was null or undefined when calling createProjectApiV2ProjectsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateToJSON(requestParameters['projectCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Create Project
     */
    async createProjectApiV2ProjectsPost(requestParameters: CreateProjectApiV2ProjectsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.createProjectApiV2ProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Project
     */
    async getProjectApiV2ProjectsProjectIdGetRaw(requestParameters: GetProjectApiV2ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getProjectApiV2ProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Get Project
     */
    async getProjectApiV2ProjectsProjectIdGet(requestParameters: GetProjectApiV2ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.getProjectApiV2ProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Project Activities
     */
    async listProjectActivitiesApiV2ProjectsProjectIdActivitiesGetRaw(requestParameters: ListProjectActivitiesApiV2ProjectsProjectIdActivitiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ActivityResponse>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listProjectActivitiesApiV2ProjectsProjectIdActivitiesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/activities`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ActivityResponseFromJSON));
    }

    /**
     * List Project Activities
     */
    async listProjectActivitiesApiV2ProjectsProjectIdActivitiesGet(requestParameters: ListProjectActivitiesApiV2ProjectsProjectIdActivitiesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ActivityResponse>> {
        const response = await this.listProjectActivitiesApiV2ProjectsProjectIdActivitiesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Projects
     */
    async listProjectsApiV2ProjectsGetRaw(requestParameters: ListProjectsApiV2ProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['teamId'] != null) {
            queryParameters['team_id'] = requestParameters['teamId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectResponseFromJSON));
    }

    /**
     * List Projects
     */
    async listProjectsApiV2ProjectsGet(requestParameters: ListProjectsApiV2ProjectsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectResponse>> {
        const response = await this.listProjectsApiV2ProjectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Project Member
     */
    async removeProjectMemberApiV2ProjectsProjectIdMembersMemberIdDeleteRaw(requestParameters: RemoveProjectMemberApiV2ProjectsProjectIdMembersMemberIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling removeProjectMemberApiV2ProjectsProjectIdMembersMemberIdDelete().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling removeProjectMemberApiV2ProjectsProjectIdMembersMemberIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/members/{member_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"member_id"}}`, encodeURIComponent(String(requestParameters['memberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Project Member
     */
    async removeProjectMemberApiV2ProjectsProjectIdMembersMemberIdDelete(requestParameters: RemoveProjectMemberApiV2ProjectsProjectIdMembersMemberIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.removeProjectMemberApiV2ProjectsProjectIdMembersMemberIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Project
     */
    async updateProjectApiV2ProjectsProjectIdPatchRaw(requestParameters: UpdateProjectApiV2ProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectApiV2ProjectsProjectIdPatch().'
            );
        }

        if (requestParameters['projectUpdate'] == null) {
            throw new runtime.RequiredError(
                'projectUpdate',
                'Required parameter "projectUpdate" was null or undefined when calling updateProjectApiV2ProjectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateToJSON(requestParameters['projectUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Update Project
     */
    async updateProjectApiV2ProjectsProjectIdPatch(requestParameters: UpdateProjectApiV2ProjectsProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.updateProjectApiV2ProjectsProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Project Member Role
     */
    async updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatchRaw(requestParameters: UpdateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatch().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatch().'
            );
        }

        if (requestParameters['projectMemberUpdateRole'] == null) {
            throw new runtime.RequiredError(
                'projectMemberUpdateRole',
                'Required parameter "projectMemberUpdateRole" was null or undefined when calling updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/projects/{project_id}/members/{member_id}`;
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"member_id"}}`, encodeURIComponent(String(requestParameters['memberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectMemberUpdateRoleToJSON(requestParameters['projectMemberUpdateRole']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectResponseFromJSON(jsonValue));
    }

    /**
     * Update Project Member Role
     */
    async updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatch(requestParameters: UpdateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectResponse> {
        const response = await this.updateProjectMemberRoleApiV2ProjectsProjectIdMembersMemberIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
