/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FetchModelsRequest,
  FetchModelsResponse,
  HTTPValidationError,
  ModelContextRequest,
  ProviderListResponse,
  ProviderUpsertRequest,
  SelectModelRequest,
  SelectModelResponse,
} from '../models/index';
import {
    FetchModelsRequestFromJSON,
    FetchModelsRequestToJSON,
    FetchModelsResponseFromJSON,
    FetchModelsResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ModelContextRequestFromJSON,
    ModelContextRequestToJSON,
    ProviderListResponseFromJSON,
    ProviderListResponseToJSON,
    ProviderUpsertRequestFromJSON,
    ProviderUpsertRequestToJSON,
    SelectModelRequestFromJSON,
    SelectModelRequestToJSON,
    SelectModelResponseFromJSON,
    SelectModelResponseToJSON,
} from '../models/index';

export interface CreateProviderApiV2ProvidersPostRequest {
    providerUpsertRequest: ProviderUpsertRequest;
}

export interface DeleteProviderApiV2ProvidersKeyDeleteRequest {
    key: string;
}

export interface FetchModelsApiV2ProvidersFetchModelsPostRequest {
    fetchModelsRequest: FetchModelsRequest;
}

export interface SelectModelApiV2ProvidersSelectPostRequest {
    selectModelRequest: SelectModelRequest;
}

export interface SetModelContextApiV2ProvidersModelsModelKeyContextPostRequest {
    modelKey: string;
    modelContextRequest: ModelContextRequest;
}

export interface UpdateProviderApiV2ProvidersKeyPutRequest {
    key: string;
    providerUpsertRequest: ProviderUpsertRequest;
}

/**
 * 
 */
export class ProvidersApi extends runtime.BaseAPI {

    /**
     * Add a provider (models fetched from /models when omitted)
     */
    async createProviderApiV2ProvidersPostRaw(requestParameters: CreateProviderApiV2ProvidersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        if (requestParameters['providerUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'providerUpsertRequest',
                'Required parameter "providerUpsertRequest" was null or undefined when calling createProviderApiV2ProvidersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProviderUpsertRequestToJSON(requestParameters['providerUpsertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * Add a provider (models fetched from /models when omitted)
     */
    async createProviderApiV2ProvidersPost(requestParameters: CreateProviderApiV2ProvidersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.createProviderApiV2ProvidersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a provider and its models
     */
    async deleteProviderApiV2ProvidersKeyDeleteRaw(requestParameters: DeleteProviderApiV2ProvidersKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling deleteProviderApiV2ProvidersKeyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * Delete a provider and its models
     */
    async deleteProviderApiV2ProvidersKeyDelete(requestParameters: DeleteProviderApiV2ProvidersKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.deleteProviderApiV2ProvidersKeyDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Probe {base_url}/models for a provider
     */
    async fetchModelsApiV2ProvidersFetchModelsPostRaw(requestParameters: FetchModelsApiV2ProvidersFetchModelsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FetchModelsResponse>> {
        if (requestParameters['fetchModelsRequest'] == null) {
            throw new runtime.RequiredError(
                'fetchModelsRequest',
                'Required parameter "fetchModelsRequest" was null or undefined when calling fetchModelsApiV2ProvidersFetchModelsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/fetch-models`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FetchModelsRequestToJSON(requestParameters['fetchModelsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FetchModelsResponseFromJSON(jsonValue));
    }

    /**
     * Probe {base_url}/models for a provider
     */
    async fetchModelsApiV2ProvidersFetchModelsPost(requestParameters: FetchModelsApiV2ProvidersFetchModelsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FetchModelsResponse> {
        const response = await this.fetchModelsApiV2ProvidersFetchModelsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List providers and their models
     */
    async listProvidersApiV2ProvidersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * List providers and their models
     */
    async listProvidersApiV2ProvidersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.listProvidersApiV2ProvidersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Switch the global default model (restarts running workers)
     */
    async selectModelApiV2ProvidersSelectPostRaw(requestParameters: SelectModelApiV2ProvidersSelectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SelectModelResponse>> {
        if (requestParameters['selectModelRequest'] == null) {
            throw new runtime.RequiredError(
                'selectModelRequest',
                'Required parameter "selectModelRequest" was null or undefined when calling selectModelApiV2ProvidersSelectPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/select`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectModelRequestToJSON(requestParameters['selectModelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SelectModelResponseFromJSON(jsonValue));
    }

    /**
     * Switch the global default model (restarts running workers)
     */
    async selectModelApiV2ProvidersSelectPost(requestParameters: SelectModelApiV2ProvidersSelectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SelectModelResponse> {
        const response = await this.selectModelApiV2ProvidersSelectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set a model\'s context window (e.g. K3 256K/512K/1M tiers)
     */
    async setModelContextApiV2ProvidersModelsModelKeyContextPostRaw(requestParameters: SetModelContextApiV2ProvidersModelsModelKeyContextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        if (requestParameters['modelKey'] == null) {
            throw new runtime.RequiredError(
                'modelKey',
                'Required parameter "modelKey" was null or undefined when calling setModelContextApiV2ProvidersModelsModelKeyContextPost().'
            );
        }

        if (requestParameters['modelContextRequest'] == null) {
            throw new runtime.RequiredError(
                'modelContextRequest',
                'Required parameter "modelContextRequest" was null or undefined when calling setModelContextApiV2ProvidersModelsModelKeyContextPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/models/{model_key}/context`;
        urlPath = urlPath.replace(`{${"model_key"}}`, encodeURIComponent(String(requestParameters['modelKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelContextRequestToJSON(requestParameters['modelContextRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * Set a model\'s context window (e.g. K3 256K/512K/1M tiers)
     */
    async setModelContextApiV2ProvidersModelsModelKeyContextPost(requestParameters: SetModelContextApiV2ProvidersModelsModelKeyContextPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.setModelContextApiV2ProvidersModelsModelKeyContextPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a provider\'s endpoint, key, or models
     */
    async updateProviderApiV2ProvidersKeyPutRaw(requestParameters: UpdateProviderApiV2ProvidersKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderListResponse>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling updateProviderApiV2ProvidersKeyPut().'
            );
        }

        if (requestParameters['providerUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'providerUpsertRequest',
                'Required parameter "providerUpsertRequest" was null or undefined when calling updateProviderApiV2ProvidersKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/providers/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProviderUpsertRequestToJSON(requestParameters['providerUpsertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderListResponseFromJSON(jsonValue));
    }

    /**
     * Update a provider\'s endpoint, key, or models
     */
    async updateProviderApiV2ProvidersKeyPut(requestParameters: UpdateProviderApiV2ProvidersKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderListResponse> {
        const response = await this.updateProviderApiV2ProvidersKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
