/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSessionRequest,
  ForkSessionRequest,
  GenerateTitleRequest,
  GenerateTitleResponse,
  GitDiffStats,
  GoalCreateRequest,
  HTTPValidationError,
  HistoryPage,
  Session,
  UpdateSessionRequest,
  UploadSessionFileResponse,
} from '../models/index';
import {
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    ForkSessionRequestFromJSON,
    ForkSessionRequestToJSON,
    GenerateTitleRequestFromJSON,
    GenerateTitleRequestToJSON,
    GenerateTitleResponseFromJSON,
    GenerateTitleResponseToJSON,
    GitDiffStatsFromJSON,
    GitDiffStatsToJSON,
    GoalCreateRequestFromJSON,
    GoalCreateRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    HistoryPageFromJSON,
    HistoryPageToJSON,
    SessionFromJSON,
    SessionToJSON,
    UpdateSessionRequestFromJSON,
    UpdateSessionRequestToJSON,
    UploadSessionFileResponseFromJSON,
    UploadSessionFileResponseToJSON,
} from '../models/index';

export interface CreateSessionApiSessionsPostRequest {
    createSessionRequest?: CreateSessionRequest;
}

export interface CreateSessionGoalApiSessionsSessionIdGoalPostRequest {
    sessionId: string;
    goalCreateRequest: GoalCreateRequest;
}

export interface DeleteSessionApiSessionsSessionIdDeleteRequest {
    sessionId: string;
}

export interface DeleteSessionGoalApiSessionsSessionIdGoalDeleteRequest {
    sessionId: string;
}

export interface ForkSessionEndpointApiSessionsSessionIdForkPostRequest {
    sessionId: string;
    forkSessionRequest: ForkSessionRequest;
}

export interface GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest {
    sessionId: string;
    generateTitleRequest?: GenerateTitleRequest;
}

export interface GetSessionApiSessionsSessionIdGetRequest {
    sessionId: string;
}

export interface GetSessionFileApiSessionsSessionIdFilesPathGetRequest {
    sessionId: string;
    path: string;
}

export interface GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest {
    sessionId: string;
}

export interface GetSessionGoalApiSessionsSessionIdGoalGetRequest {
    sessionId: string;
}

export interface GetSessionHistoryApiSessionsSessionIdHistoryGetRequest {
    sessionId: string;
    beforeLine?: number | null;
    limit?: number;
}

export interface GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest {
    sessionId: string;
    path: string;
}

export interface ListSessionSubagentsApiSessionsSessionIdSubagentsGetRequest {
    sessionId: string;
}

export interface ListSessionsApiSessionsGetRequest {
    limit?: number;
    offset?: number;
    q?: string | null;
    archived?: boolean | null;
}

export interface PauseSessionGoalApiSessionsSessionIdGoalPausePostRequest {
    sessionId: string;
}

export interface ResumeSessionGoalApiSessionsSessionIdGoalResumePostRequest {
    sessionId: string;
}

export interface UpdateSessionApiSessionsSessionIdPatchRequest {
    sessionId: string;
    updateSessionRequest: UpdateSessionRequest;
}

export interface UploadSessionFileApiSessionsSessionIdFilesPostRequest {
    sessionId: string;
    file: Blob;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     * Create a new session.
     * Create a new session
     */
    async createSessionApiSessionsPostRaw(requestParameters: CreateSessionApiSessionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Create a new session.
     * Create a new session
     */
    async createSessionApiSessionsPost(requestParameters: CreateSessionApiSessionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.createSessionApiSessionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * User-initiated goal creation (no model approval needed — this IS the user).  The goal becomes active immediately; the worker picks it up at the next turn boundary (goal.json is the IPC between web main process and worker).
     * Create a goal for the session
     */
    async createSessionGoalApiSessionsSessionIdGoalPostRaw(requestParameters: CreateSessionGoalApiSessionsSessionIdGoalPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling createSessionGoalApiSessionsSessionIdGoalPost().'
            );
        }

        if (requestParameters['goalCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'goalCreateRequest',
                'Required parameter "goalCreateRequest" was null or undefined when calling createSessionGoalApiSessionsSessionIdGoalPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}/goal`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoalCreateRequestToJSON(requestParameters['goalCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * User-initiated goal creation (no model approval needed — this IS the user).  The goal becomes active immediately; the worker picks it up at the next turn boundary (goal.json is the IPC between web main process and worker).
     * Create a goal for the session
     */
    async createSessionGoalApiSessionsSessionIdGoalPost(requestParameters: CreateSessionGoalApiSessionsSessionIdGoalPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createSessionGoalApiSessionsSessionIdGoalPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a session.
     * Delete a session
     */
    async deleteSessionApiSessionsSessionIdDeleteRaw(requestParameters: DeleteSessionApiSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteSessionApiSessionsSessionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a session.
     * Delete a session
     */
    async deleteSessionApiSessionsSessionIdDelete(requestParameters: DeleteSessionApiSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteSessionApiSessionsSessionIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancel the session goal
     */
    async deleteSessionGoalApiSessionsSessionIdGoalDeleteRaw(requestParameters: DeleteSessionGoalApiSessionsSessionIdGoalDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteSessionGoalApiSessionsSessionIdGoalDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/goal`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Cancel the session goal
     */
    async deleteSessionGoalApiSessionsSessionIdGoalDelete(requestParameters: DeleteSessionGoalApiSessionsSessionIdGoalDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deleteSessionGoalApiSessionsSessionIdGoalDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fork a session, creating a new session with history up to the specified turn.  The new session shares the same work_dir as the original session.
     * Fork a session at a specific turn
     */
    async forkSessionEndpointApiSessionsSessionIdForkPostRaw(requestParameters: ForkSessionEndpointApiSessionsSessionIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling forkSessionEndpointApiSessionsSessionIdForkPost().'
            );
        }

        if (requestParameters['forkSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'forkSessionRequest',
                'Required parameter "forkSessionRequest" was null or undefined when calling forkSessionEndpointApiSessionsSessionIdForkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}/fork`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForkSessionRequestToJSON(requestParameters['forkSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Fork a session, creating a new session with history up to the specified turn.  The new session shares the same work_dir as the original session.
     * Fork a session at a specific turn
     */
    async forkSessionEndpointApiSessionsSessionIdForkPost(requestParameters: ForkSessionEndpointApiSessionsSessionIdForkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.forkSessionEndpointApiSessionsSessionIdForkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate a concise session title using AI based on the first conversation turn.  If request body is empty or parameters are missing, the backend will automatically read the first turn from wire.jsonl.
     * Generate session title using AI
     */
    async generateSessionTitleApiSessionsSessionIdGenerateTitlePostRaw(requestParameters: GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateTitleResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling generateSessionTitleApiSessionsSessionIdGenerateTitlePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}/generate-title`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateTitleRequestToJSON(requestParameters['generateTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateTitleResponseFromJSON(jsonValue));
    }

    /**
     * Generate a concise session title using AI based on the first conversation turn.  If request body is empty or parameters are missing, the backend will automatically read the first turn from wire.jsonl.
     * Generate session title using AI
     */
    async generateSessionTitleApiSessionsSessionIdGenerateTitlePost(requestParameters: GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateTitleResponse> {
        const response = await this.generateSessionTitleApiSessionsSessionIdGenerateTitlePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a session by ID.
     * Get session
     */
    async getSessionApiSessionsSessionIdGetRaw(requestParameters: GetSessionApiSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionApiSessionsSessionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Get a session by ID.
     * Get session
     */
    async getSessionApiSessionsSessionIdGet(requestParameters: GetSessionApiSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.getSessionApiSessionsSessionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a file or list directory from session work directory.
     * Get file or list directory from session work_dir
     */
    async getSessionFileApiSessionsSessionIdFilesPathGetRaw(requestParameters: GetSessionFileApiSessionsSessionIdFilesPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionFileApiSessionsSessionIdFilesPathGet().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getSessionFileApiSessionsSessionIdFilesPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/files/{path}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get a file or list directory from session work directory.
     * Get file or list directory from session work_dir
     */
    async getSessionFileApiSessionsSessionIdFilesPathGet(requestParameters: GetSessionFileApiSessionsSessionIdFilesPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSessionFileApiSessionsSessionIdFilesPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get git diff stats for the session\'s work directory
     * Get git diff stats
     */
    async getSessionGitDiffApiSessionsSessionIdGitDiffGetRaw(requestParameters: GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitDiffStats>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionGitDiffApiSessionsSessionIdGitDiffGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/git-diff`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GitDiffStatsFromJSON(jsonValue));
    }

    /**
     * get git diff stats for the session\'s work directory
     * Get git diff stats
     */
    async getSessionGitDiffApiSessionsSessionIdGitDiffGet(requestParameters: GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitDiffStats> {
        const response = await this.getSessionGitDiffApiSessionsSessionIdGitDiffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the session goal snapshot
     */
    async getSessionGoalApiSessionsSessionIdGoalGetRaw(requestParameters: GetSessionGoalApiSessionsSessionIdGoalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionGoalApiSessionsSessionIdGoalGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/goal`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the session goal snapshot
     */
    async getSessionGoalApiSessionsSessionIdGoalGet(requestParameters: GetSessionGoalApiSessionsSessionIdGoalGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getSessionGoalApiSessionsSessionIdGoalGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Paginated history for lazy loading older messages on scroll-up.  ``before_line`` is the ``oldest_line`` cursor from the previous page; omit it for the newest page. Returns coalesced JSONRPC event strings, the next cursor (``oldest_line``) and ``has_more``.
     * Fetch an older page of session history
     */
    async getSessionHistoryApiSessionsSessionIdHistoryGetRaw(requestParameters: GetSessionHistoryApiSessionsSessionIdHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HistoryPage>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionHistoryApiSessionsSessionIdHistoryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['beforeLine'] != null) {
            queryParameters['before_line'] = requestParameters['beforeLine'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/history`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HistoryPageFromJSON(jsonValue));
    }

    /**
     * Paginated history for lazy loading older messages on scroll-up.  ``before_line`` is the ``oldest_line`` cursor from the previous page; omit it for the newest page. Returns coalesced JSONRPC event strings, the next cursor (``oldest_line``) and ``has_more``.
     * Fetch an older page of session history
     */
    async getSessionHistoryApiSessionsSessionIdHistoryGet(requestParameters: GetSessionHistoryApiSessionsSessionIdHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HistoryPage> {
        const response = await this.getSessionHistoryApiSessionsSessionIdHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a file from a session\'s uploads directory.
     * Get uploaded file from session uploads
     */
    async getSessionUploadFileApiSessionsSessionIdUploadsPathGetRaw(requestParameters: GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionUploadFileApiSessionsSessionIdUploadsPathGet().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getSessionUploadFileApiSessionsSessionIdUploadsPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/uploads/{path}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get a file from a session\'s uploads directory.
     * Get uploaded file from session uploads
     */
    async getSessionUploadFileApiSessionsSessionIdUploadsPathGet(requestParameters: GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSessionUploadFileApiSessionsSessionIdUploadsPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Snapshot of subagent instances (swarm overview), read from meta.json files.  Live updates stream over the WebSocket as `SubagentStatus` events; this endpoint provides the initial state on page load / reconnect.
     * List subagent instances of a session
     */
    async listSessionSubagentsApiSessionsSessionIdSubagentsGetRaw(requestParameters: ListSessionSubagentsApiSessionsSessionIdSubagentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listSessionSubagentsApiSessionsSessionIdSubagentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/subagents`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Snapshot of subagent instances (swarm overview), read from meta.json files.  Live updates stream over the WebSocket as `SubagentStatus` events; this endpoint provides the initial state on page load / reconnect.
     * List subagent instances of a session
     */
    async listSessionSubagentsApiSessionsSessionIdSubagentsGet(requestParameters: ListSessionSubagentsApiSessionsSessionIdSubagentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.listSessionSubagentsApiSessionsSessionIdSubagentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List sessions with optional pagination and search.  Args:     limit: Maximum number of sessions to return (default 100, max 500).     offset: Number of sessions to skip (default 0).     q: Optional search query to filter by title or work_dir.     archived: Filter by archived status.         - None (default): Only return non-archived sessions.         - True: Only return archived sessions.
     * List all sessions
     */
    async listSessionsApiSessionsGetRaw(requestParameters: ListSessionsApiSessionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Session>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionFromJSON));
    }

    /**
     * List sessions with optional pagination and search.  Args:     limit: Maximum number of sessions to return (default 100, max 500).     offset: Number of sessions to skip (default 0).     q: Optional search query to filter by title or work_dir.     archived: Filter by archived status.         - None (default): Only return non-archived sessions.         - True: Only return archived sessions.
     * List all sessions
     */
    async listSessionsApiSessionsGet(requestParameters: ListSessionsApiSessionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Session>> {
        const response = await this.listSessionsApiSessionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pause the session goal
     */
    async pauseSessionGoalApiSessionsSessionIdGoalPausePostRaw(requestParameters: PauseSessionGoalApiSessionsSessionIdGoalPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling pauseSessionGoalApiSessionsSessionIdGoalPausePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/goal/pause`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Pause the session goal
     */
    async pauseSessionGoalApiSessionsSessionIdGoalPausePost(requestParameters: PauseSessionGoalApiSessionsSessionIdGoalPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.pauseSessionGoalApiSessionsSessionIdGoalPausePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resume a paused/blocked goal. The driver continues at the next turn.
     * Resume the session goal
     */
    async resumeSessionGoalApiSessionsSessionIdGoalResumePostRaw(requestParameters: ResumeSessionGoalApiSessionsSessionIdGoalResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling resumeSessionGoalApiSessionsSessionIdGoalResumePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/goal/resume`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Resume a paused/blocked goal. The driver continues at the next turn.
     * Resume the session goal
     */
    async resumeSessionGoalApiSessionsSessionIdGoalResumePost(requestParameters: ResumeSessionGoalApiSessionsSessionIdGoalResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.resumeSessionGoalApiSessionsSessionIdGoalResumePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a session (e.g., rename title or archive/unarchive).
     * Update session
     */
    async updateSessionApiSessionsSessionIdPatchRaw(requestParameters: UpdateSessionApiSessionsSessionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling updateSessionApiSessionsSessionIdPatch().'
            );
        }

        if (requestParameters['updateSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSessionRequest',
                'Required parameter "updateSessionRequest" was null or undefined when calling updateSessionApiSessionsSessionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSessionRequestToJSON(requestParameters['updateSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Update a session (e.g., rename title or archive/unarchive).
     * Update session
     */
    async updateSessionApiSessionsSessionIdPatch(requestParameters: UpdateSessionApiSessionsSessionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.updateSessionApiSessionsSessionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a file to a session.
     * Upload file to session
     */
    async uploadSessionFileApiSessionsSessionIdFilesPostRaw(requestParameters: UploadSessionFileApiSessionsSessionIdFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSessionFileResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling uploadSessionFileApiSessionsSessionIdFilesPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadSessionFileApiSessionsSessionIdFilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/sessions/{session_id}/files`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSessionFileResponseFromJSON(jsonValue));
    }

    /**
     * Upload a file to a session.
     * Upload file to session
     */
    async uploadSessionFileApiSessionsSessionIdFilesPost(requestParameters: UploadSessionFileApiSessionsSessionIdFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSessionFileResponse> {
        const response = await this.uploadSessionFileApiSessionsSessionIdFilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
