/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  TeamCreate,
  TeamMemberUpdateRole,
  TeamProviderKeyResponse,
  TeamProviderKeyUpsertRequest,
  TeamResponse,
  TeamUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    TeamCreateFromJSON,
    TeamCreateToJSON,
    TeamMemberUpdateRoleFromJSON,
    TeamMemberUpdateRoleToJSON,
    TeamProviderKeyResponseFromJSON,
    TeamProviderKeyResponseToJSON,
    TeamProviderKeyUpsertRequestFromJSON,
    TeamProviderKeyUpsertRequestToJSON,
    TeamResponseFromJSON,
    TeamResponseToJSON,
    TeamUpdateFromJSON,
    TeamUpdateToJSON,
} from '../models/index';

export interface AddTeamMemberApiV2TeamsTeamIdMembersPostRequest {
    teamId: string;
    userId: string;
    role?: string;
}

export interface CreateTeamApiV2TeamsPostRequest {
    teamCreate: TeamCreate;
}

export interface DeleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDeleteRequest {
    teamId: string;
    providerKey: string;
}

export interface GetTeamApiV2TeamsTeamIdGetRequest {
    teamId: string;
}

export interface ListTeamProviderKeysApiV2TeamsTeamIdProviderKeysGetRequest {
    teamId: string;
}

export interface RemoveTeamMemberApiV2TeamsTeamIdMembersMemberIdDeleteRequest {
    teamId: string;
    memberId: string;
}

export interface UpdateTeamApiV2TeamsTeamIdPatchRequest {
    teamId: string;
    teamUpdate: TeamUpdate;
}

export interface UpdateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatchRequest {
    teamId: string;
    memberId: string;
    teamMemberUpdateRole: TeamMemberUpdateRole;
}

export interface UpsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPutRequest {
    teamId: string;
    providerKey: string;
    teamProviderKeyUpsertRequest: TeamProviderKeyUpsertRequest;
}

/**
 * 
 */
export class TeamsApi extends runtime.BaseAPI {

    /**
     * Add Team Member
     */
    async addTeamMemberApiV2TeamsTeamIdMembersPostRaw(requestParameters: AddTeamMemberApiV2TeamsTeamIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamResponse>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling addTeamMemberApiV2TeamsTeamIdMembersPost().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addTeamMemberApiV2TeamsTeamIdMembersPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/members`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamResponseFromJSON(jsonValue));
    }

    /**
     * Add Team Member
     */
    async addTeamMemberApiV2TeamsTeamIdMembersPost(requestParameters: AddTeamMemberApiV2TeamsTeamIdMembersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamResponse> {
        const response = await this.addTeamMemberApiV2TeamsTeamIdMembersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Team
     */
    async createTeamApiV2TeamsPostRaw(requestParameters: CreateTeamApiV2TeamsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamResponse>> {
        if (requestParameters['teamCreate'] == null) {
            throw new runtime.RequiredError(
                'teamCreate',
                'Required parameter "teamCreate" was null or undefined when calling createTeamApiV2TeamsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TeamCreateToJSON(requestParameters['teamCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamResponseFromJSON(jsonValue));
    }

    /**
     * Create Team
     */
    async createTeamApiV2TeamsPost(requestParameters: CreateTeamApiV2TeamsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamResponse> {
        const response = await this.createTeamApiV2TeamsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a team\'s API key for a provider. Team owner/admin only.
     * Delete Team Provider Key
     */
    async deleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDeleteRaw(requestParameters: DeleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling deleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDelete().'
            );
        }

        if (requestParameters['providerKey'] == null) {
            throw new runtime.RequiredError(
                'providerKey',
                'Required parameter "providerKey" was null or undefined when calling deleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/provider-keys/{provider_key}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"provider_key"}}`, encodeURIComponent(String(requestParameters['providerKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a team\'s API key for a provider. Team owner/admin only.
     * Delete Team Provider Key
     */
    async deleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDelete(requestParameters: DeleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.deleteTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Team
     */
    async getTeamApiV2TeamsTeamIdGetRaw(requestParameters: GetTeamApiV2TeamsTeamIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamResponse>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling getTeamApiV2TeamsTeamIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamResponseFromJSON(jsonValue));
    }

    /**
     * Get Team
     */
    async getTeamApiV2TeamsTeamIdGet(requestParameters: GetTeamApiV2TeamsTeamIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamResponse> {
        const response = await this.getTeamApiV2TeamsTeamIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List a team\'s stored provider keys (masked). Team owner/admin only.
     * List Team Provider Keys
     */
    async listTeamProviderKeysApiV2TeamsTeamIdProviderKeysGetRaw(requestParameters: ListTeamProviderKeysApiV2TeamsTeamIdProviderKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TeamProviderKeyResponse>>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling listTeamProviderKeysApiV2TeamsTeamIdProviderKeysGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/provider-keys`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TeamProviderKeyResponseFromJSON));
    }

    /**
     * List a team\'s stored provider keys (masked). Team owner/admin only.
     * List Team Provider Keys
     */
    async listTeamProviderKeysApiV2TeamsTeamIdProviderKeysGet(requestParameters: ListTeamProviderKeysApiV2TeamsTeamIdProviderKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TeamProviderKeyResponse>> {
        const response = await this.listTeamProviderKeysApiV2TeamsTeamIdProviderKeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Teams
     */
    async listTeamsApiV2TeamsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TeamResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TeamResponseFromJSON));
    }

    /**
     * List Teams
     */
    async listTeamsApiV2TeamsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TeamResponse>> {
        const response = await this.listTeamsApiV2TeamsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Remove Team Member
     */
    async removeTeamMemberApiV2TeamsTeamIdMembersMemberIdDeleteRaw(requestParameters: RemoveTeamMemberApiV2TeamsTeamIdMembersMemberIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling removeTeamMemberApiV2TeamsTeamIdMembersMemberIdDelete().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling removeTeamMemberApiV2TeamsTeamIdMembersMemberIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/members/{member_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"member_id"}}`, encodeURIComponent(String(requestParameters['memberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove Team Member
     */
    async removeTeamMemberApiV2TeamsTeamIdMembersMemberIdDelete(requestParameters: RemoveTeamMemberApiV2TeamsTeamIdMembersMemberIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.removeTeamMemberApiV2TeamsTeamIdMembersMemberIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Team
     */
    async updateTeamApiV2TeamsTeamIdPatchRaw(requestParameters: UpdateTeamApiV2TeamsTeamIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamResponse>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling updateTeamApiV2TeamsTeamIdPatch().'
            );
        }

        if (requestParameters['teamUpdate'] == null) {
            throw new runtime.RequiredError(
                'teamUpdate',
                'Required parameter "teamUpdate" was null or undefined when calling updateTeamApiV2TeamsTeamIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TeamUpdateToJSON(requestParameters['teamUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamResponseFromJSON(jsonValue));
    }

    /**
     * Update Team
     */
    async updateTeamApiV2TeamsTeamIdPatch(requestParameters: UpdateTeamApiV2TeamsTeamIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamResponse> {
        const response = await this.updateTeamApiV2TeamsTeamIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Team Member Role
     */
    async updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatchRaw(requestParameters: UpdateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamResponse>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatch().'
            );
        }

        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatch().'
            );
        }

        if (requestParameters['teamMemberUpdateRole'] == null) {
            throw new runtime.RequiredError(
                'teamMemberUpdateRole',
                'Required parameter "teamMemberUpdateRole" was null or undefined when calling updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/members/{member_id}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"member_id"}}`, encodeURIComponent(String(requestParameters['memberId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TeamMemberUpdateRoleToJSON(requestParameters['teamMemberUpdateRole']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamResponseFromJSON(jsonValue));
    }

    /**
     * Update Team Member Role
     */
    async updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatch(requestParameters: UpdateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamResponse> {
        const response = await this.updateTeamMemberRoleApiV2TeamsTeamIdMembersMemberIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or replace a team\'s API key for a provider. Team owner/admin only.
     * Upsert Team Provider Key
     */
    async upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPutRaw(requestParameters: UpsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TeamProviderKeyResponse>> {
        if (requestParameters['teamId'] == null) {
            throw new runtime.RequiredError(
                'teamId',
                'Required parameter "teamId" was null or undefined when calling upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPut().'
            );
        }

        if (requestParameters['providerKey'] == null) {
            throw new runtime.RequiredError(
                'providerKey',
                'Required parameter "providerKey" was null or undefined when calling upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPut().'
            );
        }

        if (requestParameters['teamProviderKeyUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'teamProviderKeyUpsertRequest',
                'Required parameter "teamProviderKeyUpsertRequest" was null or undefined when calling upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/teams/{team_id}/provider-keys/{provider_key}`;
        urlPath = urlPath.replace(`{${"team_id"}}`, encodeURIComponent(String(requestParameters['teamId'])));
        urlPath = urlPath.replace(`{${"provider_key"}}`, encodeURIComponent(String(requestParameters['providerKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TeamProviderKeyUpsertRequestToJSON(requestParameters['teamProviderKeyUpsertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamProviderKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create or replace a team\'s API key for a provider. Team owner/admin only.
     * Upsert Team Provider Key
     */
    async upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPut(requestParameters: UpsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TeamProviderKeyResponse> {
        const response = await this.upsertTeamProviderKeyApiV2TeamsTeamIdProviderKeysProviderKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
