/* tslint:disable */
/* eslint-disable */
/**
 * Cran Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CranCodeWebApiV2UsersUserResponse,
  HTTPValidationError,
  ProviderKeyResponse,
  ProviderKeyUpsertRequest,
  UsageDailyPoint,
  UsageSummary,
  UserProfileUpdate,
  UserRoleUpdate,
} from '../models/index';
import {
    CranCodeWebApiV2UsersUserResponseFromJSON,
    CranCodeWebApiV2UsersUserResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ProviderKeyResponseFromJSON,
    ProviderKeyResponseToJSON,
    ProviderKeyUpsertRequestFromJSON,
    ProviderKeyUpsertRequestToJSON,
    UsageDailyPointFromJSON,
    UsageDailyPointToJSON,
    UsageSummaryFromJSON,
    UsageSummaryToJSON,
    UserProfileUpdateFromJSON,
    UserProfileUpdateToJSON,
    UserRoleUpdateFromJSON,
    UserRoleUpdateToJSON,
} from '../models/index';

export interface DeleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDeleteRequest {
    providerKey: string;
}

export interface GetMyUsageDailyApiV2UsersMeUsageDailyGetRequest {
    days?: number;
    tz?: string | null;
}

export interface SearchUsersApiV2UsersSearchGetRequest {
    q: string;
}

export interface UpdateMeApiV2UsersMePatchRequest {
    userProfileUpdate: UserProfileUpdate;
}

export interface UpdateUserRoleApiV2UsersUserIdRolePatchRequest {
    userId: string;
    userRoleUpdate: UserRoleUpdate;
}

export interface UpsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPutRequest {
    providerKey: string;
    providerKeyUpsertRequest: ProviderKeyUpsertRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Delete the current user\'s API key for a provider.
     * Delete My Provider Key
     */
    async deleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDeleteRaw(requestParameters: DeleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        if (requestParameters['providerKey'] == null) {
            throw new runtime.RequiredError(
                'providerKey',
                'Required parameter "providerKey" was null or undefined when calling deleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me/provider-keys/{provider_key}`;
        urlPath = urlPath.replace(`{${"provider_key"}}`, encodeURIComponent(String(requestParameters['providerKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete the current user\'s API key for a provider.
     * Delete My Provider Key
     */
    async deleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDelete(requestParameters: DeleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.deleteMyProviderKeyApiV2UsersMeProviderKeysProviderKeyDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Me
     */
    async getMeApiV2UsersMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CranCodeWebApiV2UsersUserResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CranCodeWebApiV2UsersUserResponseFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMeApiV2UsersMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CranCodeWebApiV2UsersUserResponse> {
        const response = await this.getMeApiV2UsersMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Per-provider token usage summary for the current user.  Rows are grouped by ``(provider_key, source)``. Rows with ``source=\'shared\'`` additionally carry ``quota_tokens`` / ``remaining_tokens`` when a restricted-mode grant covers the user (``None`` = unlimited / not applicable).
     * Get My Usage
     */
    async getMyUsageApiV2UsersMeUsageGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsageSummary>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me/usage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageSummaryFromJSON));
    }

    /**
     * Per-provider token usage summary for the current user.  Rows are grouped by ``(provider_key, source)``. Rows with ``source=\'shared\'`` additionally carry ``quota_tokens`` / ``remaining_tokens`` when a restricted-mode grant covers the user (``None`` = unlimited / not applicable).
     * Get My Usage
     */
    async getMyUsageApiV2UsersMeUsageGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsageSummary>> {
        const response = await this.getMyUsageApiV2UsersMeUsageGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Per-day token usage for the current user over the last ``days`` days.  Rows are grouped by ``(date, provider_key, model, source)`` and ordered chronologically. Days are calendar days in the ``tz`` timezone (IANA name, default UTC); pass the browser\'s timezone for a local \"today\". ``days`` is clamped to [1, 90].
     * Get My Usage Daily
     */
    async getMyUsageDailyApiV2UsersMeUsageDailyGetRaw(requestParameters: GetMyUsageDailyApiV2UsersMeUsageDailyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsageDailyPoint>>> {
        const queryParameters: any = {};

        if (requestParameters['days'] != null) {
            queryParameters['days'] = requestParameters['days'];
        }

        if (requestParameters['tz'] != null) {
            queryParameters['tz'] = requestParameters['tz'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me/usage/daily`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsageDailyPointFromJSON));
    }

    /**
     * Per-day token usage for the current user over the last ``days`` days.  Rows are grouped by ``(date, provider_key, model, source)`` and ordered chronologically. Days are calendar days in the ``tz`` timezone (IANA name, default UTC); pass the browser\'s timezone for a local \"today\". ``days`` is clamped to [1, 90].
     * Get My Usage Daily
     */
    async getMyUsageDailyApiV2UsersMeUsageDailyGet(requestParameters: GetMyUsageDailyApiV2UsersMeUsageDailyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsageDailyPoint>> {
        const response = await this.getMyUsageDailyApiV2UsersMeUsageDailyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the current user\'s stored provider keys (masked).
     * List My Provider Keys
     */
    async listMyProviderKeysApiV2UsersMeProviderKeysGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProviderKeyResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me/provider-keys`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProviderKeyResponseFromJSON));
    }

    /**
     * List the current user\'s stored provider keys (masked).
     * List My Provider Keys
     */
    async listMyProviderKeysApiV2UsersMeProviderKeysGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProviderKeyResponse>> {
        const response = await this.listMyProviderKeysApiV2UsersMeProviderKeysGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search users by username, email, or display_name.
     * Search Users
     */
    async searchUsersApiV2UsersSearchGetRaw(requestParameters: SearchUsersApiV2UsersSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CranCodeWebApiV2UsersUserResponse>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchUsersApiV2UsersSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CranCodeWebApiV2UsersUserResponseFromJSON));
    }

    /**
     * Search users by username, email, or display_name.
     * Search Users
     */
    async searchUsersApiV2UsersSearchGet(requestParameters: SearchUsersApiV2UsersSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CranCodeWebApiV2UsersUserResponse>> {
        const response = await this.searchUsersApiV2UsersSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Me
     */
    async updateMeApiV2UsersMePatchRaw(requestParameters: UpdateMeApiV2UsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CranCodeWebApiV2UsersUserResponse>> {
        if (requestParameters['userProfileUpdate'] == null) {
            throw new runtime.RequiredError(
                'userProfileUpdate',
                'Required parameter "userProfileUpdate" was null or undefined when calling updateMeApiV2UsersMePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserProfileUpdateToJSON(requestParameters['userProfileUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CranCodeWebApiV2UsersUserResponseFromJSON(jsonValue));
    }

    /**
     * Update Me
     */
    async updateMeApiV2UsersMePatch(requestParameters: UpdateMeApiV2UsersMePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CranCodeWebApiV2UsersUserResponse> {
        const response = await this.updateMeApiV2UsersMePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change a user\'s global role (admin only).
     * Update User Role
     */
    async updateUserRoleApiV2UsersUserIdRolePatchRaw(requestParameters: UpdateUserRoleApiV2UsersUserIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CranCodeWebApiV2UsersUserResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateUserRoleApiV2UsersUserIdRolePatch().'
            );
        }

        if (requestParameters['userRoleUpdate'] == null) {
            throw new runtime.RequiredError(
                'userRoleUpdate',
                'Required parameter "userRoleUpdate" was null or undefined when calling updateUserRoleApiV2UsersUserIdRolePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/{user_id}/role`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UserRoleUpdateToJSON(requestParameters['userRoleUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CranCodeWebApiV2UsersUserResponseFromJSON(jsonValue));
    }

    /**
     * Change a user\'s global role (admin only).
     * Update User Role
     */
    async updateUserRoleApiV2UsersUserIdRolePatch(requestParameters: UpdateUserRoleApiV2UsersUserIdRolePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CranCodeWebApiV2UsersUserResponse> {
        const response = await this.updateUserRoleApiV2UsersUserIdRolePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or replace the current user\'s API key for a provider.
     * Upsert My Provider Key
     */
    async upsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPutRaw(requestParameters: UpsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProviderKeyResponse>> {
        if (requestParameters['providerKey'] == null) {
            throw new runtime.RequiredError(
                'providerKey',
                'Required parameter "providerKey" was null or undefined when calling upsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPut().'
            );
        }

        if (requestParameters['providerKeyUpsertRequest'] == null) {
            throw new runtime.RequiredError(
                'providerKeyUpsertRequest',
                'Required parameter "providerKeyUpsertRequest" was null or undefined when calling upsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v2/users/me/provider-keys/{provider_key}`;
        urlPath = urlPath.replace(`{${"provider_key"}}`, encodeURIComponent(String(requestParameters['providerKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProviderKeyUpsertRequestToJSON(requestParameters['providerKeyUpsertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProviderKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create or replace the current user\'s API key for a provider.
     * Upsert My Provider Key
     */
    async upsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPut(requestParameters: UpsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProviderKeyResponse> {
        const response = await this.upsertMyProviderKeyApiV2UsersMeProviderKeysProviderKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
